-- ----------------------------
-- Table structure for res_district
-- ----------------------------
DROP TABLE IF EXISTS `res_district`;
CREATE TABLE `res_district` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `district_no` varchar(64) NULL DEFAULT NULL COMMENT '区县编码',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '名称',
  `introduction` text NULL COMMENT '区县介绍',
  `tags` text NULL COMMENT '产业领域',
  `contact_person` varchar(64) NULL DEFAULT NULL COMMENT '联系人',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `address` text NULL COMMENT '详细地址',
  `remark` text NULL COMMENT '备注',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `data_source_id` bigint NULL DEFAULT NULL COMMENT '对应数据源id',
  `tag` text NULL COMMENT '行业数据标签',
  `cuju_chanye` text NULL COMMENT '6+5+X',
  `industry` text NULL COMMENT '所属产业',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_district_no` (`district_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源区县表';

-- ----------------------------
-- Table structure for res_carrier
-- ----------------------------
DROP TABLE IF EXISTS `res_carrier`;
CREATE TABLE `res_carrier` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `carrier_no` varchar(64) NULL DEFAULT NULL COMMENT '载体编码',
  `carrier_type` varchar(64) NULL DEFAULT NULL COMMENT '载体类型',
  `sec_type` varchar(64) NULL DEFAULT NULL COMMENT '二级分类',
  `location` varchar(64) NULL DEFAULT NULL COMMENT '载体位置',
  `address` varchar(255) NULL DEFAULT NULL COMMENT '详细地址',
  `industry_park` varchar(64) NULL DEFAULT NULL COMMENT '园区等级',
  `carrier_name` varchar(255) NULL DEFAULT NULL COMMENT '名称',
  `carrier_picture` text NULL COMMENT '载体图片',
  `carrier_intro` text NULL COMMENT '介绍',
  `contact` varchar(64) NULL DEFAULT NULL COMMENT '联系人',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `star_com` varchar(255) NULL DEFAULT NULL COMMENT '明星企业',
  `area` varchar(64) NULL DEFAULT NULL COMMENT '面积',
  `floor_height` bigint NULL DEFAULT NULL COMMENT '层高',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '产业领域',
  `available_land` varchar(64) NULL DEFAULT NULL COMMENT '可用地情况',
  `investment_area` varchar(64) NULL DEFAULT NULL COMMENT '可招商面积',
  `rent` varchar(64) NULL DEFAULT NULL COMMENT '租金',
  `remark` text NULL COMMENT '备注',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `park_type` varchar(64) NULL DEFAULT NULL COMMENT '园区类型',
  `end_of_floor` bigint NULL DEFAULT NULL COMMENT '层高结束',
  `availability_type` varchar(64) NULL DEFAULT NULL COMMENT '可用地情况',
  `leading_industries` text NULL COMMENT '主导产业',
  `total_area` bigint NULL DEFAULT NULL COMMENT '总面积',
  `data_source_id` bigint NULL DEFAULT NULL COMMENT '对应数据源id',
  `parcel_area` bigint NULL DEFAULT NULL COMMENT '地块面积',
  `tag` text NULL COMMENT '行业数据标签',
  `rent_type` varchar(64) NULL DEFAULT NULL COMMENT '租金类型',
  `minimum_rent` bigint NULL DEFAULT NULL COMMENT '租金最小值',
  `maximum_rent` bigint NULL DEFAULT NULL COMMENT '租金最大值',
  `lettable_area` bigint NULL DEFAULT NULL COMMENT '可租用面积',
  `district_county` varchar(64) NULL DEFAULT NULL COMMENT '所在区县',
  `land_use` varchar(64) NULL DEFAULT NULL COMMENT '土地用途',
  `floor_height_range` varchar(64) NULL DEFAULT NULL COMMENT '层高范围',
  `park_level` varchar(64) NULL DEFAULT NULL COMMENT '园区级别',
  `cuju_chanye` text NULL COMMENT '6+5+X',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_carrier_no` (`carrier_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='载体数据';

-- ----------------------------
-- Table structure for res_policy
-- ----------------------------
DROP TABLE IF EXISTS `res_policy`;
CREATE TABLE `res_policy` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `policy_no` varchar(64) NULL DEFAULT NULL COMMENT '政策编码',
  `policy_title` text NULL COMMENT '政策标题',
  `policy_abstract` text NULL COMMENT '政策摘要',
  `main_body` text NULL COMMENT '正文',
  `publish_time` datetime NULL DEFAULT NULL COMMENT '发布时间',
  `policy_department` varchar(64) NULL DEFAULT NULL COMMENT '发布部门',
  `source` varchar(64) NULL DEFAULT NULL COMMENT '来源',
  `link` text NULL COMMENT '原文链接',
  `effect_date` datetime NULL DEFAULT NULL COMMENT '生效日期',
  `failure_date` datetime NULL DEFAULT NULL COMMENT '失效日期',
  `status` varchar(64) NULL DEFAULT NULL COMMENT '政策状态',
  `policy_timeliness` varchar(64) NULL DEFAULT NULL COMMENT '时效性',
  `contact_name` varchar(64) NULL DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `policy_region` varchar(100) NULL DEFAULT NULL COMMENT '政策地区',
  `policy_tag` text NULL COMMENT '目标产业',
  `policy_com_type` text NULL COMMENT '适用企业类型',
  `level` varchar(64) NULL DEFAULT NULL COMMENT '政策级别',
  `attachment` text NULL COMMENT '附件',
  `policy_number` varchar(64) NULL DEFAULT NULL COMMENT '文号',
  `remark` text NULL COMMENT '备注',
  `title` varchar(255) NULL DEFAULT NULL COMMENT '标题',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_policy_no` (`policy_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='政策';

-- ----------------------------
-- Table structure for res_expert
-- ----------------------------
DROP TABLE IF EXISTS `res_expert`;
CREATE TABLE `res_expert` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `expert_no` varchar(64) NULL DEFAULT NULL COMMENT '专家编码',
  `name` varchar(64) NULL DEFAULT NULL COMMENT '专家姓名',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `location` varchar(100) NULL DEFAULT NULL COMMENT '所在地',
  `degree` varchar(64) NULL DEFAULT NULL COMMENT '学历学位',
  `major` varchar(64) NULL DEFAULT NULL COMMENT '专业',
  `major_level` varchar(64) NULL DEFAULT NULL COMMENT '专业职称等级',
  `major_type` varchar(64) NULL DEFAULT NULL COMMENT '专业类别',
  `research_industry` text NULL COMMENT '研究方向',
  `work_years` int NULL DEFAULT NULL COMMENT '工作年限',
  `work_com` varchar(255) NULL DEFAULT NULL COMMENT '工作单位',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职位',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '所属产业链',
  `is_lecturer` varchar(64) NULL DEFAULT NULL COMMENT '是否能纳入培训讲师',
  `expert_type` varchar(64) NULL DEFAULT NULL COMMENT '专家类型',
  `expert_level` varchar(64) NULL DEFAULT NULL COMMENT '专家级别',
  `source` varchar(64) NULL DEFAULT NULL COMMENT '专家来源',
  `remark` text NULL COMMENT '备注',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `industry_sj` text NULL COMMENT '所属产业',
  `is_partner` tinyint(1) NULL DEFAULT NULL COMMENT '是否合作伙伴: 0否 1是',
  `profile` text NULL COMMENT '简介',
  `institution_type` varchar(64) NULL DEFAULT NULL COMMENT '机构类型',
  `contact_number` varchar(24) NULL DEFAULT NULL COMMENT '联系电话',
  `affiliated_institutions` text NULL COMMENT '所属机构',
  `entry_person` bigint NULL DEFAULT NULL COMMENT '录入人',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_expert_no` (`expert_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='专家';

-- ----------------------------
-- Table structure for res_scenario
-- ----------------------------
DROP TABLE IF EXISTS `res_scenario`;
CREATE TABLE `res_scenario` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `scenario_no` varchar(64) NULL DEFAULT NULL COMMENT '场景编码',
  `publish_time` datetime NULL DEFAULT NULL COMMENT '发布时间',
  `owner_unit` varchar(64) NULL DEFAULT NULL COMMENT '业主单位',
  `scene_name` varchar(255) NULL DEFAULT NULL COMMENT '场景名称',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '所属产业',
  `opportunity_zone` varchar(100) NULL DEFAULT NULL COMMENT '机会区域',
  `validity_period` varchar(255) NULL DEFAULT NULL COMMENT '机会有效期',
  `budget_guarantee` text NULL COMMENT '预算保障情况',
  `other_situations` text NULL COMMENT '其他情况',
  `opportunity_desc` text NULL COMMENT '机会描述',
  `build_basement` text NULL COMMENT '建设基础',
  `cooperation_requirements` text NULL COMMENT '合作需求',
  `cooperation_form` text NULL COMMENT '合作形式',
  `contact_person` varchar(64) NULL DEFAULT NULL COMMENT '联系人',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职务',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `remark` text NULL COMMENT '备注',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `industrial_fields` text NULL COMMENT '产业领域',
  `xcuju_chanye` text NULL COMMENT '6+5+X',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_scenario_no` (`scenario_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='场景';

-- ----------------------------
-- Table structure for res_industry_chain
-- ----------------------------
DROP TABLE IF EXISTS `res_industry_chain`;
CREATE TABLE `res_industry_chain` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `industry_chain_no` varchar(64) NULL DEFAULT NULL COMMENT '产业链编码',
  `industry_chain_name` varchar(255) NULL DEFAULT NULL COMMENT '产业链名称',
  `industry_chain_intro` text NULL COMMENT '产业链介绍',
  `industry_chain_map` text NULL COMMENT '产业链图谱',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `graph_layer` text NULL COMMENT '图谱配置',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_industry_chain_no` (`industry_chain_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产业链';

-- ----------------------------
-- Table structure for res_thinktank
-- ----------------------------
DROP TABLE IF EXISTS `res_thinktank`;
CREATE TABLE `res_thinktank` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `thinktank_no` varchar(64) NULL DEFAULT NULL COMMENT '新研机构编码',
  `brief_name` varchar(64) NULL DEFAULT NULL COMMENT '企业简称',
  `full_name` text NULL COMMENT '企业全称',
  `com_other_name` text NULL COMMENT '其他简称',
  `logo` text NULL COMMENT '企业logo',
  `com_type` varchar(64) NULL DEFAULT NULL COMMENT '企业类型',
  `website` text NULL COMMENT '企业网址',
  `brief_intro` text NULL COMMENT '一句话简介',
  `detail_intro` text NULL COMMENT '企业介绍',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `invest_round` decimal(14, 0) NULL DEFAULT NULL COMMENT '当前轮次',
  `invest_round_name` varchar(64) NULL DEFAULT NULL COMMENT '当前轮次名称',
  `operating_status` decimal(14, 0) NULL DEFAULT NULL COMMENT '运营状态',
  `operating_status_name` varchar(64) NULL DEFAULT NULL COMMENT '运营状态名称',
  `staff` varchar(64) NULL DEFAULT NULL COMMENT '人员规模',
  `baike_link` text NULL COMMENT '百度百科链接',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签',
  `industry_name` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签名称',
  `market_valuation_rmb` decimal(18, 4) NULL DEFAULT NULL COMMENT '公司最新市值/估值-亿元',
  `tags` text NULL COMMENT '企业全部标签',
  `location` varchar(255) NULL DEFAULT NULL COMMENT '所在地',
  `address` text NULL COMMENT '详细地址',
  `cooperation_type` text NULL COMMENT '合作类别',
  `cooperation_form` text NULL COMMENT '合作形式',
  `resource_analysis` text NULL COMMENT '资源方穿透分析',
  `construction_content` text NULL COMMENT '建设内容',
  `industry_focus` text NULL COMMENT '聚焦产业领域',
  `cooperation_units` text NULL COMMENT '合作单位',
  `business_focus` varchar(64) NULL DEFAULT NULL COMMENT '业务侧重',
  `operation_mode` varchar(64) NULL DEFAULT NULL COMMENT '运营模式',
  `responsible_department` varchar(64) NULL DEFAULT NULL COMMENT '主责部门',
  `research_topic` text NULL COMMENT '在研课题及相关进度',
  `remark` text NULL COMMENT '备注',
  `reg_full_name` text NULL COMMENT '注册名称',
  `reg_time` datetime NULL DEFAULT NULL COMMENT '注册时间',
  `reg_location` text NULL COMMENT '注册地址',
  `reg_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本（万）',
  `reg_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本币种',
  `reg_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '注册资本币种名称',
  `paid_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本（万）',
  `paid_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本币种',
  `paid_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '实缴资本币种名称',
  `reg_type` decimal(14, 0) NULL DEFAULT NULL COMMENT '企业注册类型',
  `reg_type_name` varchar(64) NULL DEFAULT NULL COMMENT '企业注册类型名称',
  `legal_represent` varchar(64) NULL DEFAULT NULL COMMENT '法人代表',
  `reg_number` varchar(64) NULL DEFAULT NULL COMMENT '工商注册号',
  `credit_number` varchar(64) NULL DEFAULT NULL COMMENT '统一社会信用代码',
  `business_period` text NULL COMMENT '营业期限',
  `business_scope` text NULL COMMENT '经营范围',
  `reg_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业名称',
  `reg_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业门类名称',
  `reg_sub_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业大类',
  `reg_sub_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业大类名称',
  `reg_middle_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业中类',
  `reg_middle_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业中类名称',
  `reg_small_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业小类',
  `reg_small_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业小类名称',
  `reg_institute` varchar(64) NULL DEFAULT NULL COMMENT '登记机关',
  `approve_time` datetime NULL DEFAULT NULL COMMENT '核准日期',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `partner` tinyint(1) NULL DEFAULT NULL COMMENT '是否合作伙伴: 0否 1是',
  `platform_resources` text NULL COMMENT '平台资源',
  `contact` text NULL COMMENT '联系人',
  `contact_number` varchar(24) NULL DEFAULT NULL COMMENT '联系电话',
  `duties` text NULL COMMENT '职务',
  `location_china` varchar(100) NULL DEFAULT NULL COMMENT '所在地',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_thinktank_no` (`thinktank_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='新研机构';

-- ----------------------------
-- Table structure for res_thinktank_fund
-- ----------------------------
DROP TABLE IF EXISTS `res_thinktank_fund`;
CREATE TABLE `res_thinktank_fund` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `fund_name` varchar(255) NULL DEFAULT NULL COMMENT '基金名称',
  `fund_scale` varchar(255) NULL DEFAULT NULL COMMENT '基金规模',
  `thinktank_id` bigint NULL DEFAULT NULL COMMENT '新研机构-数据主键id',
  `invest_industry` text NULL COMMENT '投资行业偏好',
  `round_prefer` text NULL COMMENT '投资阶段偏好',
  `single_invest_amount` varchar(64) NULL DEFAULT NULL COMMENT '单笔投资金额',
  `invest_method` text NULL COMMENT '投资方式',
  `investable_balance` decimal(16, 2) NULL DEFAULT NULL COMMENT '可投余额',
  `return_requirements` text NULL COMMENT '返投要求',
  `completion_status` text NULL COMMENT '返投完成情况',
  `fund_type` varchar(64) NULL DEFAULT NULL COMMENT '基金类型',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `investment_industries` text NULL COMMENT '投资产业',
  `available_balance_of_fund` varchar(64) NULL DEFAULT NULL COMMENT '基金可投余额',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='新研机构基金';

-- ----------------------------
-- Table structure for res_thinktank_plat
-- ----------------------------
DROP TABLE IF EXISTS `res_thinktank_plat`;
CREATE TABLE `res_thinktank_plat` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `platform_name` varchar(255) NULL DEFAULT NULL COMMENT '共性平台名称',
  `thinktank_id` bigint NULL DEFAULT NULL COMMENT '新研机构-数据主键id',
  `support_facilities` text NULL COMMENT '配套设施',
  `platform_type` varchar(64) NULL DEFAULT NULL COMMENT '平台分类',
  `service_industry` text NULL COMMENT '服务领域',
  `service_object` text NULL COMMENT '服务对象',
  `service_capability` text NULL COMMENT '服务能力',
  `service_content` text NULL COMMENT '服务内容',
  `qualification` text NULL COMMENT '已获资质情况',
  `remark` text NULL COMMENT '备注',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `service_field` text NULL COMMENT '服务产业',
  `tag` text NULL COMMENT '行业数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='新研机构共性平台';

-- ----------------------------
-- Table structure for res_thinktank_member
-- ----------------------------
DROP TABLE IF EXISTS `res_thinktank_member`;
CREATE TABLE `res_thinktank_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `thinktank_id` bigint NULL DEFAULT NULL COMMENT '新研机构-数据主键id',
  `person_name` varchar(64) NULL DEFAULT NULL COMMENT '姓名',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职位',
  `person_intro` text NULL COMMENT '个人介绍',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `edu_background` varchar(255) NULL DEFAULT NULL COMMENT '学历',
  `enterprise_id` bigint NULL DEFAULT NULL COMMENT '企业-数据主键id',
  `rank_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '排序字段',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='新研机构团队人员';

-- ----------------------------
-- Table structure for res_finance
-- ----------------------------
DROP TABLE IF EXISTS `res_finance`;
CREATE TABLE `res_finance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `finance_no` varchar(64) NULL DEFAULT NULL COMMENT '金融编码',
  `brief_name` varchar(64) NULL DEFAULT NULL COMMENT '机构简称',
  `full_name` text NULL COMMENT '企业全称',
  `com_other_name` text NULL COMMENT '其它简称',
  `logo` text NULL COMMENT '企业Logo',
  `com_type` varchar(64) NULL DEFAULT NULL COMMENT '企业类型',
  `website` text NULL COMMENT '企业网址',
  `brief_intro` text NULL COMMENT '一句话简介',
  `detail_intro` text NULL COMMENT '企业介绍',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `invest_round` decimal(14, 0) NULL DEFAULT NULL COMMENT '当前轮次',
  `operating_status` decimal(14, 0) NULL DEFAULT NULL COMMENT '运营状态',
  `staff` varchar(64) NULL DEFAULT NULL COMMENT '人员规模',
  `baike_link` text NULL COMMENT '百度百科链接',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签',
  `industry_name` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签名称',
  `market_valuation_rmb` decimal(18, 4) NULL DEFAULT NULL COMMENT '公司最新市值/估值-亿元',
  `tags` text NULL COMMENT '企业全部标签',
  `reg_full_name` text NULL COMMENT '注册名称',
  `reg_time` datetime NULL DEFAULT NULL COMMENT '注册时间',
  `reg_location` text NULL COMMENT '注册地址',
  `reg_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本（万）',
  `reg_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本币种',
  `paid_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本（万）',
  `paid_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本币种',
  `reg_type` decimal(14, 0) NULL DEFAULT NULL COMMENT '企业注册类型',
  `legal_represent` varchar(255) NULL DEFAULT NULL COMMENT '法人代表',
  `reg_number` varchar(64) NULL DEFAULT NULL COMMENT '工商注册号',
  `credit_number` varchar(64) NULL DEFAULT NULL COMMENT '统一社会信用代码',
  `business_period` text NULL COMMENT '营业期限',
  `business_scope` text NULL COMMENT '经营范围',
  `reg_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业门类',
  `reg_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业门类名称',
  `reg_sub_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业大类',
  `reg_sub_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业大类名称',
  `reg_middle_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业中类',
  `reg_middle_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业中类名称',
  `reg_small_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业小类',
  `reg_small_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业小类名称',
  `reg_institute` varchar(64) NULL DEFAULT NULL COMMENT '登记机关',
  `approve_time` datetime NULL DEFAULT NULL COMMENT '核准日期',
  `location` varchar(100) NULL DEFAULT NULL COMMENT '所在地',
  `fin_type` varchar(64) NULL DEFAULT NULL COMMENT '金融机构类型',
  `fin_nature` varchar(64) NULL DEFAULT NULL COMMENT '机构性质',
  `is_confidential` varchar(64) NULL DEFAULT NULL COMMENT '是否签订保密协议',
  `cooperation_time` datetime NULL DEFAULT NULL COMMENT '合作建立时间',
  `cooperativeness` text NULL COMMENT '合作程度',
  `cooperation_scope` text NULL COMMENT '合作范围',
  `remark` text NULL COMMENT '备注',
  `invest_round_name` varchar(64) NULL DEFAULT NULL COMMENT '当前轮次名称',
  `operating_status_name` varchar(64) NULL DEFAULT NULL COMMENT '运营状态名称',
  `reg_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '注册资本币种名称',
  `paid_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '实缴资本币种名称',
  `reg_type_name` varchar(64) NULL DEFAULT NULL COMMENT '企业注册类型名称',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `position_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '挂职人数',
  `position_advanced_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '高级挂职人数',
  `tag` text NULL COMMENT '行业数据标签',
  `docking_person` varchar(64) NULL DEFAULT NULL COMMENT '对接人',
  `corresponding_source_id` decimal(14, 0) NULL DEFAULT NULL COMMENT '对应数据源id',
  `docking_personnel` text NULL COMMENT '对接人员',
  `level` varchar(64) NULL DEFAULT NULL COMMENT '级别',
  `partner` tinyint(1) NULL DEFAULT NULL COMMENT '是否合作伙伴: 0否 1是',
  `warehousing_time` date NULL DEFAULT NULL COMMENT '入库时间',
  `contact` text NULL COMMENT '联系人',
  `contact_number` varchar(24) NULL DEFAULT NULL COMMENT '联系电话',
  `entry_person` bigint NULL DEFAULT NULL COMMENT '录入人',
  `contact_information` text NULL COMMENT '联系方式',
  `mailbox` varchar(64) NULL DEFAULT NULL COMMENT '邮箱',
  `duties` text NULL COMMENT '职务',
  `activities_undertaken` text NULL COMMENT '拟开展活动',
  `logo_picture` text NULL COMMENT 'logo图片',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_finance_no` (`finance_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='金融机构';

-- ----------------------------
-- Table structure for res_finance_member
-- ----------------------------
DROP TABLE IF EXISTS `res_finance_member`;
CREATE TABLE `res_finance_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `finance_id` bigint NULL DEFAULT NULL COMMENT '金融机构-数据主键id',
  `person_name` varchar(64) NULL DEFAULT NULL COMMENT '姓名',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职位',
  `person_intro` text NULL COMMENT '个人介绍',
  `rank_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '排序字段',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `edu_background` varchar(255) NULL DEFAULT NULL COMMENT '学历',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='金融机构团队人员';

-- ----------------------------
-- Table structure for res_finance_product
-- ----------------------------
DROP TABLE IF EXISTS `res_finance_product`;
CREATE TABLE `res_finance_product` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `product_name` varchar(255) NULL DEFAULT NULL COMMENT '产品名称',
  `finance_id` bigint NULL DEFAULT NULL COMMENT '所属机构',
  `product_intro` text NULL COMMENT '产品特点',
  `product_features` text NULL COMMENT '产品特点',
  `apply_condition` text NULL COMMENT '申请条件',
  `apply_material` text NULL COMMENT '申请资料',
  `product_type` varchar(64) NULL DEFAULT NULL COMMENT '金融产品类型',
  `product_group` text NULL COMMENT '适用客户类型',
  `quota_limit` decimal(16, 2) NULL DEFAULT NULL COMMENT '额度(万元)',
  `rate_limit` decimal(16, 2) NULL DEFAULT NULL COMMENT '利率',
  `term_imit` varchar(64) NULL DEFAULT NULL COMMENT '期限',
  `guarantee_method` varchar(64) NULL DEFAULT NULL COMMENT '担保方式',
  `max_credit_term` varchar(64) NULL DEFAULT NULL COMMENT '授信最长期限',
  `guarantee_limit` varchar(64) NULL DEFAULT NULL COMMENT '担保类额度上限',
  `asset_collateral_ratio_limit` varchar(64) NULL DEFAULT NULL COMMENT '资产抵押率上限',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `corresponding_source_id` decimal(14, 0) NULL DEFAULT NULL COMMENT '对应数据源id',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='金融机构产品';

-- ----------------------------
-- Table structure for res_enterprise
-- ----------------------------
DROP TABLE IF EXISTS `res_enterprise`;
CREATE TABLE `res_enterprise` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `enterprise_no` varchar(64) NULL DEFAULT NULL COMMENT '企业编码',
  `brief_name` varchar(64) NULL DEFAULT NULL COMMENT '企业简称',
  `full_name` text NULL COMMENT '企业全称',
  `com_other_name` text NULL COMMENT '其它简称',
  `logo` text NULL COMMENT '企业Logo',
  `com_type` varchar(64) NULL DEFAULT NULL COMMENT '企业类型',
  `website` text NULL COMMENT '企业网址',
  `brief_intro` text NULL COMMENT '一句话简介',
  `detail_intro` text NULL COMMENT '企业介绍',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `invest_round` decimal(14, 0) NULL DEFAULT NULL COMMENT '当前轮次',
  `operating_status` decimal(14, 0) NULL DEFAULT NULL COMMENT '运营状态',
  `staff` varchar(64) NULL DEFAULT NULL COMMENT '人员规模',
  `baike_link` text NULL COMMENT '百度百科链接',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签',
  `industry_name` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签名称',
  `market_valuation_rmb` decimal(18, 4) NULL DEFAULT NULL COMMENT '公司最新市值/估值-亿元',
  `tags` text NULL COMMENT '企业全部标签',
  `latest_investment_id` varchar(64) NULL DEFAULT NULL COMMENT '最新融资id',
  `latest_invest_time` datetime NULL DEFAULT NULL COMMENT '最新融资时间',
  `latest_exposure_time` datetime NULL DEFAULT NULL COMMENT '最新融资曝光时间',
  `latest_invest_round` decimal(14, 0) NULL DEFAULT NULL COMMENT '最新融资轮次',
  `latest_invest_amount_type` decimal(14, 0) NULL DEFAULT NULL COMMENT '最新融资金额类型',
  `latest_invest_amount` varchar(64) NULL DEFAULT NULL COMMENT '最新融资金额',
  `unified_invest_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '最新融资金额转化（单位：万）',
  `latest_invest_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '最新融资金融币种',
  `latest_investor` text NULL COMMENT '最新融资投资方',
  `investment_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '历史融资次数',
  `total_investors` text NULL COMMENT '历史投资方',
  `total_invest_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '历史融资总额（统一化：万元）',
  `external_investment_count` decimal(14, 0) NULL DEFAULT NULL COMMENT '对外投资总数',
  `company_contact` text NULL COMMENT '联系信息',
  `organizational_structure` text NULL COMMENT '企业组织架构',
  `securities_info` text NULL COMMENT '证券信息',
  `reg_full_name` text NULL COMMENT '注册名称',
  `reg_time` datetime NULL DEFAULT NULL COMMENT '注册时间',
  `reg_location` text NULL COMMENT '注册地址',
  `reg_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本（万）',
  `reg_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本币种',
  `paid_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本（万）',
  `paid_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本币种',
  `reg_type` decimal(14, 0) NULL DEFAULT NULL COMMENT '企业注册类型',
  `legal_represent` varchar(255) NULL DEFAULT NULL COMMENT '法人代表',
  `reg_number` varchar(64) NULL DEFAULT NULL COMMENT '工商注册号',
  `credit_number` varchar(64) NULL DEFAULT NULL COMMENT '统一社会信用代码',
  `business_period` text NULL COMMENT '营业期限',
  `business_scope` text NULL COMMENT '经营范围',
  `reg_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业门类',
  `reg_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业门类名称',
  `reg_sub_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业大类',
  `reg_sub_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业大类名称',
  `reg_middle_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业中类',
  `reg_middle_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业中类名称',
  `reg_small_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业小类',
  `reg_small_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业小类名称',
  `reg_institute` varchar(64) NULL DEFAULT NULL COMMENT '登记机关',
  `approve_time` datetime NULL DEFAULT NULL COMMENT '核准日期',
  `invest_round_name` varchar(64) NULL DEFAULT NULL COMMENT '当前轮次名称',
  `operating_status_name` varchar(64) NULL DEFAULT NULL COMMENT '运营状态名称',
  `latest_invest_round_name` varchar(64) NULL DEFAULT NULL COMMENT '最新融资轮次名称',
  `reg_type_name` varchar(64) NULL DEFAULT NULL COMMENT '企业注册类型名称',
  `reg_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '注册资本币种名称',
  `paid_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '实缴资本币种名称',
  `latest_invest_amount_type_name` varchar(64) NULL DEFAULT NULL COMMENT '最新融资金额类型名称',
  `latest_invest_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '最新融资金额币种名称',
  `remark` text NULL COMMENT '备注',
  `industry_status` text NULL COMMENT '行业地位',
  `pecuniary_condition` text NULL COMMENT '财务情况',
  `tech_advanced` text NULL COMMENT '技术先进性',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `logo_picture` text NULL COMMENT 'logo图片',
  `organizational_structure_new` text NULL COMMENT '组织架构（新）',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_enterprise_no` (`enterprise_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业';

-- ----------------------------
-- Table structure for res_enterprise_member
-- ----------------------------
DROP TABLE IF EXISTS `res_enterprise_member`;
CREATE TABLE `res_enterprise_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `enterprise_id` bigint NULL DEFAULT NULL COMMENT '企业-数据主键id',
  `person_name` varchar(64) NULL DEFAULT NULL COMMENT '姓名',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职位',
  `person_intro` text NULL COMMENT '个人介绍',
  `rank_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '排序字段',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `edu_background` varchar(255) NULL DEFAULT NULL COMMENT '学历',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '行业数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业团队人员';

-- ----------------------------
-- Table structure for res_invest
-- ----------------------------
DROP TABLE IF EXISTS `res_invest`;
CREATE TABLE `res_invest` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `invest_no` varchar(64) NULL DEFAULT NULL COMMENT '投资编码',
  `brief_name` varchar(64) NULL DEFAULT NULL COMMENT '机构简称',
  `full_name` text NULL COMMENT '企业全称',
  `com_other_name` text NULL COMMENT '其它简称',
  `logo` text NULL COMMENT '企业Logo',
  `com_type` varchar(64) NULL DEFAULT NULL COMMENT '企业类型',
  `website` text NULL COMMENT '企业网址',
  `brief_intro` text NULL COMMENT '一句话简介',
  `detail_intro` text NULL COMMENT '企业介绍',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `invest_round` decimal(14, 0) NULL DEFAULT NULL COMMENT '当前轮次',
  `operating_status` decimal(14, 0) NULL DEFAULT NULL COMMENT '运营状态',
  `staff` varchar(64) NULL DEFAULT NULL COMMENT '人员规模',
  `baike_link` text NULL COMMENT '百度百科链接',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签',
  `industry_name` varchar(64) NULL DEFAULT NULL COMMENT '一级行业标签名称',
  `market_valuation_rmb` decimal(18, 4) NULL DEFAULT NULL COMMENT '公司最新市值/估值-亿元',
  `tags` text NULL COMMENT '企业全部标签',
  `reg_full_name` text NULL COMMENT '注册名称',
  `reg_time` datetime NULL DEFAULT NULL COMMENT '注册时间',
  `reg_location` text NULL COMMENT '注册地址',
  `reg_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本（万）',
  `reg_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '注册资本币种',
  `paid_capital` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本（万）',
  `paid_capital_currency` decimal(14, 0) NULL DEFAULT NULL COMMENT '实缴资本币种',
  `reg_type` decimal(14, 0) NULL DEFAULT NULL COMMENT '企业注册类型',
  `legal_represent` varchar(255) NULL DEFAULT NULL COMMENT '法人代表',
  `reg_number` varchar(64) NULL DEFAULT NULL COMMENT '工商注册号',
  `credit_number` varchar(64) NULL DEFAULT NULL COMMENT '统一社会信用代码',
  `business_period` text NULL COMMENT '营业期限',
  `business_scope` text NULL COMMENT '经营范围',
  `reg_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业门类',
  `reg_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业门类名称',
  `reg_sub_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业大类',
  `reg_sub_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业大类名称',
  `reg_middle_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业中类',
  `reg_middle_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业中类名称',
  `reg_small_industry` decimal(14, 0) NULL DEFAULT NULL COMMENT '行业小类',
  `reg_small_industry_name` varchar(64) NULL DEFAULT NULL COMMENT '行业小类名称',
  `reg_institute` varchar(64) NULL DEFAULT NULL COMMENT '登记机关',
  `approve_time` datetime NULL DEFAULT NULL COMMENT '核准日期',
  `location` varchar(100) NULL DEFAULT NULL COMMENT '所在地',
  `org_nature` varchar(64) NULL DEFAULT NULL COMMENT '机构性质',
  `is_cvc` varchar(64) NULL DEFAULT NULL COMMENT '是否产业CVC',
  `cvc_desc` text NULL COMMENT '产业CVC描述',
  `mgt_scale` varchar(255) NULL DEFAULT NULL COMMENT '管理规模',
  `invest_industry` text NULL COMMENT '投资行业',
  `single_invest_amount` varchar(255) NULL DEFAULT NULL COMMENT '单笔投资金额',
  `round_prefer` text NULL COMMENT '投资阶段偏好',
  `invest_method` text NULL COMMENT '投资方式',
  `invest_case` text NULL COMMENT '投资案例',
  `star_proj` text NULL COMMENT '明星项目',
  `main_demands` text NULL COMMENT '主要诉求/痛点',
  `remark` text NULL COMMENT '备注',
  `invest_round_name` varchar(64) NULL DEFAULT NULL COMMENT '当前轮次名称',
  `operating_status_name` varchar(64) NULL DEFAULT NULL COMMENT '运营状态名称',
  `reg_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '注册资本币种名称',
  `paid_capital_currency_name` varchar(64) NULL DEFAULT NULL COMMENT '实缴资本币种名称',
  `reg_type_name` varchar(64) NULL DEFAULT NULL COMMENT '企业注册类型名称',
  `invest_type` text NULL COMMENT '投资类型',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `need_investor_type` varchar(64) NULL DEFAULT NULL COMMENT '是否需要产业投资人、财务投资人',
  `investable_balance` decimal(16, 2) NULL DEFAULT NULL COMMENT '可投余额',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `investment_field` text NULL COMMENT '投资领域',
  `tag` text NULL COMMENT '行业数据标签',
  `docking_person` varchar(64) NULL DEFAULT NULL COMMENT '对接人',
  `docking_personnel` text NULL COMMENT '对接人员',
  `level` varchar(64) NULL DEFAULT NULL COMMENT '级别',
  `partner` tinyint(1) NULL DEFAULT NULL COMMENT '是否合作伙伴: 0否 1是',
  `docking_content` text NULL COMMENT '对接内容',
  `whether_confidentiality_agre` tinyint(1) NULL DEFAULT NULL COMMENT '是否签订保密协议',
  `duties` text NULL COMMENT '职务',
  `mailbox` varchar(64) NULL DEFAULT NULL COMMENT '邮箱',
  `completion_reverse_invest` text NULL COMMENT '反投完成情况',
  `available_balance` text NULL COMMENT '可投余额',
  `dockee` text NULL COMMENT '对接方',
  `entry_person` bigint NULL DEFAULT NULL COMMENT '录入人',
  `fund_name` text NULL COMMENT '基金名称',
  `contact` text NULL COMMENT '联系人',
  `counterinvestment_requirements` text NULL COMMENT '反投要求',
  `warehousing_time` date NULL DEFAULT NULL COMMENT '入库时间',
  `contact_information` text NULL COMMENT '联系方式',
  `investment_preferences` text NULL COMMENT '投资偏好',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_invest_no` (`invest_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资机构';

-- ----------------------------
-- Table structure for res_invest_member
-- ----------------------------
DROP TABLE IF EXISTS `res_invest_member`;
CREATE TABLE `res_invest_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `invest_id` bigint NULL DEFAULT NULL COMMENT '投资机构-数据主键id',
  `person_name` varchar(64) NULL DEFAULT NULL COMMENT '姓名',
  `position` varchar(64) NULL DEFAULT NULL COMMENT '职位',
  `person_intro` text NULL COMMENT '个人介绍',
  `rank_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '排序字段',
  `phone` varchar(64) NULL DEFAULT NULL COMMENT '联系方式',
  `edu_background` varchar(255) NULL DEFAULT NULL COMMENT '学历',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资机构团队人员';

-- ----------------------------
-- Table structure for res_invest_fund
-- ----------------------------
DROP TABLE IF EXISTS `res_invest_fund`;
CREATE TABLE `res_invest_fund` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `invest_id` bigint NULL DEFAULT NULL COMMENT '投资机构-数据主键id',
  `fund_name` varchar(255) NULL DEFAULT NULL COMMENT '基金名称',
  `fund_scale` varchar(255) NULL DEFAULT NULL COMMENT '基金规模',
  `invest_industry` text NULL COMMENT '投资行业',
  `round_prefer` text NULL COMMENT '投资阶段偏好',
  `single_invest_amount` varchar(64) NULL DEFAULT NULL COMMENT '单笔投资金额',
  `invest_method` text NULL COMMENT '投资方式',
  `investable_balance` decimal(16, 2) NULL DEFAULT NULL COMMENT '可投余额',
  `return_requirements` text NULL COMMENT '返投要求',
  `completion_status` text NULL COMMENT '返投完成情况',
  `fund_type` varchar(64) NULL DEFAULT NULL COMMENT '基金类型',
  `establish_time` datetime NULL DEFAULT NULL COMMENT '成立时间',
  `data_source` varchar(255) NULL DEFAULT NULL COMMENT '数据来源',
  `is_blacklist` tinyint(1) DEFAULT 0 COMMENT '是否负面清单: 0否 1是',
  `investment_field` text NULL COMMENT '投资领域',
  `available_balance_fund` varchar(64) NULL DEFAULT NULL COMMENT '基金可投余额',
  `tag` text NULL COMMENT '行业数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投资机构基金';
