
-- ----------------------------
-- Table structure for biz_leads
-- ----------------------------
DROP TABLE IF EXISTS `biz_leads`;
CREATE TABLE `biz_leads` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `leads_no` varchar(64) NULL DEFAULT NULL COMMENT '线索编码',
  `company_name` varchar(255) NULL DEFAULT NULL COMMENT '公司名称',
  `region` varchar(100) NULL DEFAULT NULL COMMENT '所在区域',
  `mobile` varchar(24) NULL DEFAULT NULL COMMENT '手机',
  `telephone` varchar(24) NULL DEFAULT NULL COMMENT '电话',
  `email` varchar(64) NULL DEFAULT NULL COMMENT '邮箱',
  `leads_source` varchar(256) NULL DEFAULT NULL COMMENT '线索来源',
  `flow_status` varchar(256) NULL DEFAULT NULL COMMENT '跟进状态',
  `distribution_status` varchar(256) NULL DEFAULT NULL COMMENT '分配状态',
  `transformation_status` varchar(256) NULL DEFAULT NULL COMMENT '转化状态',
  `leads_pool` bigint NULL DEFAULT NULL COMMENT '线索池',
  `marketing_activity` bigint NULL DEFAULT NULL COMMENT '营销活动',
  `promotion_channel` varchar(256) NULL DEFAULT NULL COMMENT '推广渠道',
  `return_reason` varchar(256) NULL DEFAULT NULL COMMENT '退回/回收原因',
  `return_reason_description` text NULL COMMENT '退回/回收原因说明',
  `return_time` datetime NULL DEFAULT NULL COMMENT '退回/回收时间',
  `distribution_time` datetime NULL DEFAULT NULL COMMENT '分配/领取时间',
  `leads_description` text NULL COMMENT '线索说明',
  `customer_id` bigint NULL DEFAULT NULL COMMENT '客户id',
  `contact_id` bigint NULL DEFAULT NULL COMMENT '联系人id',
  `business_id` bigint NULL DEFAULT NULL COMMENT '业务id',
  `transformation_time` datetime NULL DEFAULT NULL COMMENT '转化时间',
  `sex` varchar(256) NULL DEFAULT NULL COMMENT '性别',
  `department` varchar(255) NULL DEFAULT NULL COMMENT '部门',
  `job_title` varchar(255) NULL DEFAULT NULL COMMENT '职位',
  `age` int NULL DEFAULT NULL COMMENT '年龄',
  `birthday` datetime NULL DEFAULT NULL COMMENT '生日',
  `wechat` varchar(255) NULL DEFAULT NULL COMMENT '微信',
  `qq` varchar(255) NULL DEFAULT NULL COMMENT 'QQ',
  `fax` varchar(255) NULL DEFAULT NULL COMMENT '传真',
  `company_address` varchar(255) NULL DEFAULT NULL COMMENT '公司地址',
  `company_phone` varchar(255) NULL DEFAULT NULL COMMENT '公司电话',
  `industry` longtext NULL COMMENT '所属行业',
  `staff_size` varchar(256) NULL DEFAULT NULL COMMENT '人员规模',
  `company_email` varchar(64) NULL DEFAULT NULL COMMENT '公司邮箱',
  `company_fax` varchar(255) NULL DEFAULT NULL COMMENT '公司传真',
  `last_flow_time` datetime NULL DEFAULT NULL COMMENT '最近跟进时间',
  `handover_description` text NULL COMMENT '移交说明',
  `distribution_description` text NULL COMMENT '分配说明',
  `get_time` datetime NULL DEFAULT NULL COMMENT '获取时间',
  `country_region` longtext NULL COMMENT '国家地区',
  `return_origin_pool` tinyint(1) NULL DEFAULT NULL COMMENT '退回原池',
  `business_license` varchar(255) NULL DEFAULT NULL COMMENT '营业执照',
  `gm_name` varchar(255) NULL DEFAULT NULL COMMENT '总经理姓名',
  `sales_experience` tinyint(1) NULL DEFAULT NULL COMMENT '是否有销售经验',
  `sales_description` text NULL COMMENT '销售经验简述',
  `annual_sales` varchar(255) NULL DEFAULT NULL COMMENT '年销售额',
  `same_industry` tinyint(1) NULL DEFAULT NULL COMMENT '是否是同一领域的其他公司/品牌的合作伙伴',
  `company_brand` text NULL COMMENT '具体公司和品牌',
  `other_information` text NULL COMMENT '其他信息',
  `company_web` varchar(1000) NULL DEFAULT NULL COMMENT '公司网址',
  `license_valid` datetime NULL DEFAULT NULL COMMENT '执照有效期',
  `sales_years` decimal(14, 0) NULL DEFAULT NULL COMMENT '累计销售年数',
  `sales_dept_user_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '销售部门人数',
  `marketing_dept_user_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '营销部门人数',
  `service_dept_user_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '服务部门人数',
  `other_dept_user_num` decimal(14, 0) NULL DEFAULT NULL COMMENT '其他部门人数',
  `role` varchar(256) NULL DEFAULT NULL COMMENT '角色',
  `enterprise_type` text NULL COMMENT '企业类型',
  `start_date` datetime NULL DEFAULT NULL COMMENT '活动开始时间',
  `end_date` datetime NULL DEFAULT NULL COMMENT '活动结束时间',
  `activity_city` varchar(100) NULL DEFAULT NULL COMMENT '活动城市',
  `sponsor` varchar(255) NULL DEFAULT NULL COMMENT '主办方',
  `activity_name` varchar(255) NULL DEFAULT NULL COMMENT '活动名称',
  `own_bu` varchar(64) NULL DEFAULT NULL COMMENT '客户于合作方向所属BU',
  `cooperation_direction` text NULL COMMENT '合作方向',
  `solution` text NULL COMMENT '额外的产品/解决方案需求',
  `contact_status` varchar(64) NULL DEFAULT NULL COMMENT '联系状态',
  `signed_project` text NULL COMMENT '签约项目',
  `estimated_gross_profit` decimal(14, 0) NULL DEFAULT NULL COMMENT '预计毛利',
  `base_currency` varchar(64) NULL DEFAULT NULL COMMENT '基准货币',
  `exchange_rate` varchar(255) NULL DEFAULT NULL COMMENT '汇率',
  `expected_signing_time` datetime NULL DEFAULT NULL COMMENT '预计签约时间',
  `follow_up_person` bigint NULL DEFAULT NULL COMMENT '跟进人',
  `feedback_results` text NULL COMMENT '反馈结果',
  `new_old_customer` varchar(64) NULL DEFAULT NULL COMMENT '新客/老客',
  `customer_partner` varchar(64) NULL DEFAULT NULL COMMENT '客户/合作伙伴',
  `industry_qs` varchar(64) NULL DEFAULT NULL COMMENT '所属行业',
  `stage` text NULL COMMENT '阶段',
  `origin_data_owner_id` bigint NULL DEFAULT NULL COMMENT '原归属人',
  `first_get_from_pool` tinyint(1) NULL DEFAULT 0 COMMENT '是否为从池内的第一次获取',
  `audit_start_user` bigint NULL DEFAULT NULL COMMENT '审批发起人',
  `audit_code` varchar(255) NULL DEFAULT NULL COMMENT '审批编号',
  `audit_status` varchar(64) NULL DEFAULT NULL COMMENT '审批状态',
  `audit_start_time` datetime NULL DEFAULT NULL COMMENT '审批发起时间',
  `audit_end_time` datetime NULL DEFAULT NULL COMMENT '审批结束时间',
  `activity_city_text` varchar(64) NULL DEFAULT NULL COMMENT '活动城市（文本）',
  `history_data_owner_id` text NULL COMMENT '历史归属人信息',
  `leader_assigned` text NULL COMMENT '市领导交办',
  `bureau_leader_assigned` text NULL COMMENT '局领导交办',
  `origin_notes` text NULL COMMENT '来源备注',
  `district` varchar(64) NULL DEFAULT NULL COMMENT '区县',
  `platform_company` varchar(64) NULL DEFAULT NULL COMMENT '平台公司',
  `from_city_plan` tinyint(1) NULL DEFAULT 0 COMMENT '是否来自"创投城市计划"生态合伙人',
  `service_advisor` bigint NULL DEFAULT NULL COMMENT '市级服务专员',
  `service_advisor_contact_way` varchar(64) NULL DEFAULT NULL COMMENT '市级服务专员联系方式',
  `industry_affiliation` varchar(64) NULL DEFAULT NULL COMMENT '所属产业',
  `investor_origin_place` varchar(64) NULL DEFAULT NULL COMMENT '投资方来源地',
  `foreign_investment` tinyint(1) NULL DEFAULT 0 COMMENT '是否外资',
  `bp_attachment` text NULL COMMENT 'BP附件',
  `proposed_project_name` varchar(64) NULL DEFAULT NULL COMMENT '拟投项目名称',
  `register_money` decimal(16, 2) NULL DEFAULT NULL COMMENT '注册资金（万元）',
  `total_investment_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '总投资额（亿元）',
  `tax_estimation` decimal(16, 2) NULL DEFAULT NULL COMMENT '纳税预估（万元）',
  `recruitment_plan_content` text NULL COMMENT '招引谋划内容',
  `share_parallel_classes` tinyint(1) NULL DEFAULT 0 COMMENT '是否共享平行专班',
  `residence_place` varchar(64) NULL DEFAULT NULL COMMENT '拟落户地',
  `leads_recommender` varchar(255) NULL DEFAULT NULL COMMENT '线索推荐方',
  `leads_provide_org` bigint NULL DEFAULT NULL COMMENT '线索提供部门/机构',
  `leads_owner` bigint NULL DEFAULT NULL COMMENT '线索归属人员',
  `input_time` datetime NULL DEFAULT NULL COMMENT '线索录入时间',
  `invest_project_name` varchar(255) NULL DEFAULT NULL COMMENT '拟投资项目名称',
  `tech_advanced` varchar(255) NULL DEFAULT NULL COMMENT '技术先进性',
  `landing_content` text NULL COMMENT '落地内容',
  `tool_carrier` varchar(255) NULL DEFAULT NULL COMMENT '载体',
  `production_factors` varchar(255) NULL DEFAULT NULL COMMENT '生产要素',
  `financing` varchar(255) NULL DEFAULT NULL COMMENT '融资',
  `market` varchar(255) NULL DEFAULT NULL COMMENT '场景/市场',
  `policy` varchar(255) NULL DEFAULT NULL COMMENT '政策',
  `is_share_cyzb` varchar(64) NULL DEFAULT NULL COMMENT '是否共享产业专班',
  `is_distribute_task` tinyint(1) NULL DEFAULT 0 COMMENT '同时下发行业研判任务',
  `is_share_leads` tinyint(1) NULL DEFAULT 0 COMMENT '同时与行业牵头人共享线索',
  `invest_company` bigint NULL DEFAULT NULL COMMENT '投资方名称',
  `phase_status` varchar(64) NULL DEFAULT NULL COMMENT '阶段状态',
  `importance` varchar(64) NULL DEFAULT NULL COMMENT '重要性',
  `enterprise_demand` text NULL COMMENT '企业诉求',
  `lead_department_for_clues` bigint NULL DEFAULT NULL COMMENT '线索牵头部门',
  `analysis_content` text NULL COMMENT '研判内容',
  `judgment_opinion` varchar(64) NULL DEFAULT NULL COMMENT '研判意见',
  `reason_termination` varchar(64) NULL DEFAULT NULL COMMENT '线索终止原因',
  `destermiantion` text NULL COMMENT '终止说明',
  `technical_advantages` text NULL COMMENT '技术优势',
  `bp_attachments` text NULL COMMENT 'BP附件库',
  `docking_type` varchar(64) NULL DEFAULT NULL COMMENT '对接形式',
  `docking_info` text NULL COMMENT '对接情况',
  `industry_status` text NULL COMMENT '行业地位',
  `pecuniary_condition` text NULL COMMENT '财务情况',
  `core_advantages` text NULL COMMENT '核心优势',
  `leads_origin` varchar(64) NULL DEFAULT NULL COMMENT '线索来源',
  `invest_round` varchar(64) NULL DEFAULT NULL COMMENT '拟投资轮次',
  `need_industry` tinyint(1) NULL DEFAULT 0 COMMENT '是否需要产业投资人',
  `need_finance` tinyint(1) NULL DEFAULT 0 COMMENT '是否需要财务投资人',
  `enterprise_type` text NULL COMMENT '企业类型(多选)',
  `industry_qs_label` varchar(64) NULL DEFAULT NULL COMMENT '所属行业-中文名',
  `importance_new` varchar(64) NULL DEFAULT NULL COMMENT '重要性',
  `bureau_leads_id` varchar(64) NULL DEFAULT NULL COMMENT '市局系统线索主键id',
  `investor_origin_place_code` varchar(100) NULL DEFAULT NULL COMMENT '投资方来源地(省市区)',
  `tag` text NULL COMMENT '数据标签',
  `maximum_factory_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租金最大值',
  `leased_area` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租用面积',
  `period` varchar(64) NULL DEFAULT NULL COMMENT '期限',
  `factory_rent_type` varchar(64) NULL DEFAULT NULL COMMENT '厂房租金类型',
  `floor_height_starts` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房层高开始',
  `park_level` varchar(64) NULL DEFAULT NULL COMMENT '园区等级',
  `land_area_required` decimal(14, 0) NULL DEFAULT NULL COMMENT '需地块面积',
  `minimum_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇租金最小值',
  `whether_there_is_a_need_for_de` tinyint(1) NULL DEFAULT NULL COMMENT '是否有债权融资需求',
  `minimum_factory_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租金最小值',
  `end_of_floor_height` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房层高结束',
  `investment_area` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇招商面积',
  `park_type` varchar(64) NULL DEFAULT NULL COMMENT '园区类型',
  `maximum_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇租金最大值',
  `interest_rate` decimal(14, 0) NULL DEFAULT NULL COMMENT '利率',
  `land_use` varchar(64) NULL DEFAULT NULL COMMENT '土地用途',
  `quota` varchar(64) NULL DEFAULT NULL COMMENT '额度',
  `guarantee_methods` text NULL COMMENT '担保方式',
  `rent_type` varchar(64) NULL DEFAULT NULL COMMENT '楼宇租金类型',
  `financing_amount_100_million_y` decimal(16, 2) NULL DEFAULT NULL COMMENT '融资金额(亿元)',
  `external_clue_id` varchar(64) NULL DEFAULT NULL COMMENT '外部推荐线索id',
  `clue_researcher` bigint NULL DEFAULT NULL COMMENT '线索研判人',
  `assessment_team` text NULL COMMENT '研判团队',
  `enterpriseintermediary_contact` bigint NULL DEFAULT NULL COMMENT '企业/中介机构联系人',
  `proportion_of_equity_sold` decimal(16, 2) NULL DEFAULT NULL COMMENT '出售股权比例',
  `bureau_clue_progress` text NULL COMMENT '市局线索进度',
  `current_transfer_market_value` decimal(16, 2) NULL DEFAULT NULL COMMENT '当前转让市值',
  `operating_income_last_year` decimal(16, 2) NULL DEFAULT NULL COMMENT '去年营业收入',
  `detailed_description` text NULL COMMENT '详细描述',
  `time_requirements_before` date NULL DEFAULT NULL COMMENT '时间要求（之前）',
  `whether_to_gamble_on_performan` varchar(64) NULL DEFAULT NULL COMMENT '是否业绩对赌',
  `whether_it_is_a_listed_company` varchar(64) NULL DEFAULT NULL COMMENT '是否上市公司',
  `city_code` varchar(100) NULL DEFAULT NULL COMMENT '所属城市(省市区)',
  `financial_situation_in_the_pas` text NULL COMMENT '近三年财务情况',
  `actual_controller_situation` text NULL COMMENT '实际控制人情况',
  `requirements_for_acquirers` text NULL COMMENT '对收购方要求',
  `transfer_consideration_transac` decimal(16, 2) NULL DEFAULT NULL COMMENT '转让对价（交易金额）',
  `seller` text NULL COMMENT '出售方',
  `need_further_understanding_of` text NULL COMMENT '需要进一步了解问题',
  `project_matchmaker` bigint NULL DEFAULT NULL COMMENT '项目对接人',
  `country` varchar(64) NULL DEFAULT NULL COMMENT '国家',
  `listing_plate` varchar(64) NULL DEFAULT NULL COMMENT '上市板块',
  `latest_valuation` decimal(16, 2) NULL DEFAULT NULL COMMENT '最新估值',
  `reason_for_selling` text NULL COMMENT '出售原因',
  `net_profit_last_year` decimal(16, 2) NULL DEFAULT NULL COMMENT '去年净利润',
  `can_we_promise_to_implement_pr` varchar(64) NULL DEFAULT NULL COMMENT '能否承诺落地产能或总部搬迁',
  `performance_commitment` text NULL COMMENT '业绩承诺',
  `main_business_main_products_an` text NULL COMMENT '主营业务、主要产品及客户情况',
  `project_introduction` text NULL COMMENT '项目介绍',
  `city_dock_user_phone` varchar(64) NULL DEFAULT NULL COMMENT '市级服务专员联系方式',
  `project_clue_contact_person` varchar(64) NULL DEFAULT NULL COMMENT '项目线索联系人',
  `city_dock_user_name` varchar(64) NULL DEFAULT NULL COMMENT '市级服务专员姓名',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_leads_no` (`leads_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='线索';

-- ----------------------------
-- Table structure for biz_leads_res
-- ----------------------------
DROP TABLE IF EXISTS `biz_leads_res`;
CREATE TABLE `biz_leads_res` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `leads_id` bigint NULL DEFAULT NULL COMMENT '线索id',
  `code` varchar(64) NULL DEFAULT NULL COMMENT '自动编号',
  `agency_type` varchar(64) NULL DEFAULT NULL COMMENT '资源类型',
  `finance_id` bigint NULL DEFAULT NULL COMMENT '金融机构',
  `invest_id` bigint NULL DEFAULT NULL COMMENT '投资机构',
  `thinktank_id` bigint NULL DEFAULT NULL COMMENT '新研机构',
  `scene_id` bigint NULL DEFAULT NULL COMMENT '场景',
  `district_id` bigint NULL DEFAULT NULL COMMENT '区县id',
  `carrier_id` bigint NULL DEFAULT NULL COMMENT '载体id',
  `tag` text NULL COMMENT '数据标签',
  `policy_id` bigint NULL DEFAULT NULL COMMENT '政策id',
  `buyer_id` bigint NULL DEFAULT NULL COMMENT '买方id',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='线索资源库';


DROP TABLE IF EXISTS `biz_project`;
CREATE TABLE `biz_project`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `project_no` varchar(64) NULL DEFAULT NULL COMMENT '项目编号',
  `name` varchar(255) NULL DEFAULT NULL COMMENT '客户名称',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  `source` varchar(256) NULL DEFAULT NULL COMMENT '客户来源',
  `last_flow_time` datetime NULL DEFAULT NULL COMMENT '最近跟进时间',
  `transaction_status` varchar(256) NULL DEFAULT NULL COMMENT '成交状态',
  `recycle_time` datetime NULL DEFAULT NULL COMMENT '退回时间',
  `distribution_status` varchar(256) NULL DEFAULT NULL COMMENT '分配状态',
  `base_currency` decimal(19, 5) NULL DEFAULT NULL,
  `exchange_rate` varchar(255) NULL DEFAULT NULL COMMENT '汇率',
  `recycle_reason` varchar(256) NULL DEFAULT NULL COMMENT '退回/回收原因',
  `pool_id` bigint NULL DEFAULT NULL,
  `code` varchar(256) NULL DEFAULT NULL COMMENT '客户编号',
  `get_time` datetime NULL DEFAULT NULL COMMENT '获取时间',
  `distribution_time` datetime NULL DEFAULT NULL COMMENT '领取/分配时间',
  `handover_objects` varchar(256) NULL DEFAULT NULL COMMENT '同时移交客户关联的业务对象',
  `handover_retain_owner` tinyint(1) NULL DEFAULT NULL COMMENT '移交保留归属人在团队',
  `other_handover_retain_owner` tinyint(1) NULL DEFAULT NULL COMMENT '其他对象移交保留归属人在团队',
  `recycle_start_time` datetime NULL DEFAULT NULL COMMENT '回收计算起始时间',
  `audit_code` varchar(255) NULL DEFAULT NULL COMMENT '审批编号',
  `audit_start_time` datetime NULL DEFAULT NULL COMMENT '审批发起时间',
  `audit_end_time` datetime NULL DEFAULT NULL COMMENT '审批结束时间',
  `audit_status` varchar(256) NULL DEFAULT '0' COMMENT '审批状态',
  `audit_msg` text NULL COMMENT '审批留言',
  `apply_time` datetime NULL DEFAULT NULL COMMENT '申请时间',
  `origin_data_owner_id` bigint NULL DEFAULT NULL COMMENT '原归属人',
  `audit_start_user` bigint NULL DEFAULT NULL COMMENT '审批发起人',
  `first_get_from_pool` tinyint(1) NULL DEFAULT 0 COMMENT '是否为第一次从池里获取',
  `contact_user` bigint NULL DEFAULT NULL COMMENT '联系人',
  `remark` text NULL COMMENT '备注',
  `generation_date` datetime NULL DEFAULT NULL COMMENT '项目生成时间',
  `fixed_investment_remark` text NULL COMMENT '固投备注',
  `source_of_investment` varchar(100) NULL DEFAULT NULL COMMENT '投资来源地',
  `total_investment_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '总投资额（亿）',
  `fixed_assets_investment` decimal(16, 2) NULL DEFAULT NULL COMMENT '固定资产投资额（亿）',
  `investment_area` varchar(64) NULL DEFAULT NULL COMMENT '投资区域',
  `municipal_service_tel` varchar(64) NULL DEFAULT NULL COMMENT '市级服务专员联系方式',
  `project_labels` text NULL COMMENT '项目标签',
  `expected_signing_time` datetime NULL DEFAULT NULL COMMENT '预计签约时间',
  `investment_type` varchar(64) NULL DEFAULT NULL COMMENT '投资类型',
  `belong_industry_chain` varchar(64) NULL DEFAULT NULL COMMENT '所属产业链',
  `industry` varchar(64) NULL DEFAULT NULL COMMENT '行业',
  `industry_sector` varchar(64) NULL DEFAULT NULL COMMENT '行业领域',
  `is_foreign_investment` tinyint(1) NULL DEFAULT 0 COMMENT '是否外资',
  `is_acquire_land` tinyint(1) NULL DEFAULT 0 COMMENT '是否拿地',
  `promotion_types` varchar(64) NULL DEFAULT NULL COMMENT '推进形式',
  `project_content` text NULL COMMENT '项目内容',
  `advance_plan` text NULL COMMENT '推进计划',
  `judging_materials` text NULL COMMENT '研判材料',
  `list_of_clue_source` varchar(64) NULL DEFAULT NULL COMMENT '清单线索来源',
  `leader_of_municipal_trans` text NULL COMMENT '市交办领导',
  `leader_of_bureau_trans` text NULL COMMENT '局交办领导',
  `source_remark` text NULL COMMENT '来源备注',
  `dept` varchar(64) NULL DEFAULT NULL COMMENT '部门',
  `district` varchar(64) NULL DEFAULT NULL COMMENT '区县',
  `platform_company` varchar(64) NULL DEFAULT NULL COMMENT '平台公司',
  `is_city_plan_partner` tinyint(1) NULL DEFAULT 0 COMMENT '是否来自“创投城市计划”生态合伙人',
  `enterprise_type` text NULL COMMENT '企业类型',
  `investor_profile` text NULL COMMENT '投资方简介',
  `project_contact` varchar(64) NULL DEFAULT NULL COMMENT '项目联系人',
  `enterprise_contact_info` varchar(64) NULL DEFAULT NULL COMMENT '企业联系方式',
  `referrer` varchar(64) NULL DEFAULT NULL COMMENT '引荐人',
  `referrer_contact_info` varchar(64) NULL DEFAULT NULL COMMENT '引荐人联系方式',
  `project_phase` varchar(64) NULL DEFAULT NULL COMMENT '在谈节点',
  `phase_id` varchar(64) NULL DEFAULT NULL COMMENT '项目阶段',
  `bp_attachments` text NULL COMMENT 'BP附件库',
  `stress` varchar(64) NULL DEFAULT NULL COMMENT '重要性',
  `industry_type` varchar(64) NULL DEFAULT NULL COMMENT '行业分类',
  `city` varchar(64) NULL DEFAULT NULL COMMENT '所在城市',
  `invest_company` bigint NULL DEFAULT NULL COMMENT '投资方名称',
  `item_provide_department` bigint NULL DEFAULT NULL COMMENT '项目提供部门/机构',
  `item_recommender` varchar(64) NULL DEFAULT NULL COMMENT '项目推荐方',
  `item_recommend_time` datetime NULL DEFAULT NULL COMMENT '项目推荐时间',
  `lead_department` bigint NULL DEFAULT NULL COMMENT '牵头部门',
  `distribute_task` tinyint(1) NULL DEFAULT 0 COMMENT '同时下发行业研判任务',
  `share_item` tinyint(1) NULL DEFAULT 0 COMMENT '同时与行业牵头人或产业专班共享项目',
  `land_content` text NULL COMMENT '落地内容',
  `enterprise_appeal` text NULL COMMENT '企业诉求',
  `carrier` varchar(255) NULL DEFAULT NULL COMMENT '载体',
  `production_factors` varchar(255) NULL DEFAULT NULL COMMENT '生产要素',
  `capital` varchar(255) NULL DEFAULT NULL COMMENT '融资/资本',
  `scene` varchar(255) NULL DEFAULT NULL COMMENT '场景/市场',
  `policy` varchar(255) NULL DEFAULT NULL COMMENT '政策',
  `investment_promote_user` bigint NULL DEFAULT NULL COMMENT '投促推进人',
  `dock_district` varchar(100) NULL DEFAULT NULL COMMENT '对接区县',
  `item_progress` text NULL COMMENT '项目进展',
  `capital_factor` tinyint(1) NULL DEFAULT 0 COMMENT '资本要素',
  `capital_assessment_content` text NULL COMMENT '研判内容',
  `capital_assessment_view` varchar(64) NULL DEFAULT NULL COMMENT '资本要素-研判意见',
  `scene_factor` tinyint(1) NULL DEFAULT 0 COMMENT '场景要素',
  `scene_assessment_content` text NULL COMMENT '场景要素-研判内容',
  `scene_assessment_view` varchar(64) NULL DEFAULT NULL COMMENT '场景要素-研判意见',
  `area_factor` tinyint(1) NULL DEFAULT 0 COMMENT '场地要素',
  `area_assessment_content` text NULL COMMENT '场地要素-研判内容',
  `area_assessment_view` varchar(64) NULL DEFAULT NULL COMMENT '场地要素-研判意见',
  `policy_factor` tinyint(1) NULL DEFAULT 0 COMMENT '政策要素',
  `policy_assessment_content` text NULL COMMENT '政策要素-研判内容',
  `policy_assessment_view` varchar(64) NULL DEFAULT NULL COMMENT '政策要素-研判意见',
  `item_owner_name` bigint NULL DEFAULT NULL COMMENT '项目归属人员',
  `related_rask` bigint NULL DEFAULT NULL COMMENT '关联任务',
  `related_lead` bigint NULL DEFAULT NULL COMMENT '关联线索',
  `win_rate` decimal(14, 0) NULL DEFAULT NULL COMMENT '赢率',
  `project_contact_info` varchar(255) NULL DEFAULT NULL COMMENT '项目联系方式',
  `project_type` varchar(64) NULL DEFAULT NULL COMMENT '项目类型',
  `assessment_content` text NULL COMMENT '研判内容',
  `assessment_view` varchar(64) NULL DEFAULT NULL COMMENT '研判意见',
  `core_advantages` text NULL COMMENT '核心优势',
  `industry_status` text NULL COMMENT '行业地位',
  `financial_situation` text NULL COMMENT '财务情况',
  `speed` varchar(64) NULL DEFAULT NULL COMMENT '进度',
  `invest_round` varchar(64) NULL DEFAULT NULL COMMENT '拟投资轮次',
  `need_industry` tinyint(1) NULL DEFAULT 0 COMMENT '是否需要产业投资人',
  `need_finance` tinyint(1) NULL DEFAULT 0 COMMENT '是否需要财务投资人',
  `industry_type_cn` varchar(255) NULL DEFAULT NULL COMMENT '行业分类-中文',
  `bureau_project_id` varchar(64) NULL DEFAULT NULL COMMENT '市局项目id',
  `invest_company_name` varchar(64) NULL DEFAULT NULL COMMENT '投资方名称（与市局对接预留字段）',
  `city_code` varchar(100) NULL DEFAULT NULL COMMENT '所属城市(省市区)',
  `capital_invest_info` text NULL COMMENT '资本要素的投资信息（json）',
  `tag` text NULL COMMENT '数据标签',
  `financing_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '融资金额(亿元)',
  `building_investment_area` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇招商面积',
  `guarantee_methods` text NULL COMMENT '担保方式',
  `period` varchar(64) NULL DEFAULT NULL COMMENT '期限',
  `factory_rental_area` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租用面积',
  `factory_floor_height_begins` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房层高开始',
  `quota` varchar(64) NULL DEFAULT NULL COMMENT '额度',
  `park_type` varchar(64) NULL DEFAULT NULL COMMENT '园区类型',
  `minimum_rental_value` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇租金最小值',
  `maximum_factory_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租金最大值',
  `whether_there_is_a_need_for_de` tinyint(1) NULL DEFAULT NULL COMMENT '是否有债权融资需求',
  `end_of_factory_floor_height` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房层高结束',
  `maximum_rental_value` decimal(14, 0) NULL DEFAULT NULL COMMENT '楼宇租金最大值',
  `minimum_factory_rent` decimal(14, 0) NULL DEFAULT NULL COMMENT '厂房租金最小值',
  `land_use` varchar(64) NULL DEFAULT NULL COMMENT '土地用途',
  `park_level` varchar(64) NULL DEFAULT NULL COMMENT '园区等级',
  `type_of_building_rent` varchar(64) NULL DEFAULT NULL COMMENT '楼宇租金类型',
  `land_area_required` decimal(14, 0) NULL DEFAULT NULL COMMENT '需地块面积',
  `factory_rent_type` varchar(64) NULL DEFAULT NULL COMMENT '厂房租金类型',
  `interest_rate` decimal(14, 0) NULL DEFAULT NULL COMMENT '利率',
  `clue_researcher` bigint NULL DEFAULT NULL COMMENT '线索研判人',
  `assessment_team` text NULL COMMENT '研判团队',
  `equity_financing_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '股权融资金额',
  `bond_financing_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '债券融资金额',
  `similar_financial_amount` decimal(16, 2) NULL DEFAULT NULL COMMENT '类金融融资金额',
  `bureau_project_progress` text NULL COMMENT '市局项目进度',
  `country` varchar(64) NULL DEFAULT NULL COMMENT '国家',
  `issue_id` varchar(64) NULL DEFAULT NULL COMMENT '市局项目轮次id',
  `project_introduction` text NULL COMMENT '项目介绍',
  `issue_type` varchar(64) NULL DEFAULT NULL COMMENT '问题类型',
  `area_dock_content` text NULL COMMENT '区级对接情况',
  `money_value` varchar(64) NULL DEFAULT NULL COMMENT '问题金额',
  `issue_content` text NULL COMMENT '问题描述',
  `area_advice` text NULL COMMENT '区级建议',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE,
  KEY `idx_project_no` (`project_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目';

-- ----------------------------
-- Table structure for biz_project_partner
-- ----------------------------
DROP TABLE IF EXISTS `biz_project_partner`;
CREATE TABLE `biz_project_partner` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `project_id` bigint NULL DEFAULT NULL COMMENT '项目id',
  `relation_project` bigint NULL DEFAULT NULL COMMENT '关联项目',
  `relation_partner` bigint NULL DEFAULT NULL COMMENT '关联合作伙伴',
  `organization` varchar(64) NULL DEFAULT NULL COMMENT '机构',
  `investment_amount` decimal(14, 0) NULL DEFAULT NULL COMMENT '投资金额',
  `unit` varchar(64) NULL DEFAULT NULL COMMENT '单位',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目合作伙伴';

-- ----------------------------
-- Table structure for biz_project_phase_plan
-- ----------------------------
DROP TABLE IF EXISTS `biz_project_phase_plan`;
CREATE TABLE `biz_project_phase_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `project_id` bigint NULL DEFAULT NULL COMMENT '项目id',
  `item_phase_id` varchar(64) NULL DEFAULT NULL COMMENT '项目阶段',
  `plan_finish_time` datetime NULL DEFAULT NULL COMMENT '计划完成时间',
  `actual_finish_time` datetime NULL DEFAULT NULL COMMENT '实际完成时间',
  `tag` text NULL COMMENT '数据标签',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目阶段计划';

-- ----------------------------
-- Table structure for biz_project_res
-- ----------------------------
DROP TABLE IF EXISTS `biz_project_res`;
CREATE TABLE `biz_project_res` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` int(11) unsigned DEFAULT '0' COMMENT '租户ID字段',
  `project_id` bigint NULL DEFAULT NULL COMMENT '项目id',
  `agency_type` varchar(64) NULL DEFAULT NULL COMMENT '资源类型',
  `finance_id` bigint NULL DEFAULT NULL COMMENT '金融机构',
  `invest_id` bigint NULL DEFAULT NULL COMMENT '投资机构',
  `thinktank_id` bigint NULL DEFAULT NULL COMMENT '新研机构',
  `scene_id` bigint NULL DEFAULT NULL COMMENT '场景',
  `district_id` bigint NULL DEFAULT NULL COMMENT '区县id',
  `carrier_id` bigint NULL DEFAULT NULL COMMENT '载体id',
  `carrier_info_id` bigint NULL DEFAULT NULL COMMENT '载体数据id',
  `tag` text NULL COMMENT '数据标签',
  `policy_id` bigint NULL DEFAULT NULL COMMENT '政策id',
  `created_at` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `created_by` bigint NULL DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `updated_by` bigint NULL DEFAULT NULL COMMENT '修改人',
  `deleted_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目资源库信息';
