-- 字典数据规范化脚本
-- 生成时间: 2026-04-10
-- 数据来源: dict_data.csv

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 字典主表数据
TRUNCATE TABLE `sys_dict`;

INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10001, '客户来源', 'customer_source', 1, '字典名称: 客户来源', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10002, '清单项线索来源', 'list_item_lead_source', 1, '字典名称: 清单项线索来源', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10003, '成员状态', 'member_status', 1, '字典名称: 成员状态', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10004, '企业类型', 'enterprise_type', 1, '字典名称: 企业类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10005, '国家地区', 'country_region', 1, '字典名称: 国家地区', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10006, '活动类型', 'activity_type', 1, '字典名称: 活动类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10007, '举办方式', 'event_mode', 1, '字典名称: 举办方式', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10008, '生效类型', 'effective_type', 1, '字典名称: 生效类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10009, '人员规模', 'company_size', 1, '字典名称: 人员规模', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10010, '邀请结果', 'invite_result', 1, '字典名称: 邀请结果', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10011, '终止原因', 'termination_reason', 1, '字典名称: 终止原因', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10012, '活动相关方角色定位', 'activity_party_role', 1, '字典名称: 活动相关方角色定位', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10013, '任务事项', 'task_item', 1, '字典名称: 任务事项', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10014, '投资机构级别', 'investor_level', 1, '字典名称: 投资机构级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10015, '线索来源', 'lead_source', 1, '字典名称: 线索来源', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10016, '计算分值方式', 'score_calculation_method', 1, '字典名称: 计算分值方式', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10017, '载体类型', 'carrier_type', 1, '字典名称: 载体类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10018, '合作伙伴类型', 'partner_type', 1, '字典名称: 合作伙伴类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10019, '进度', 'progress', 1, '字典名称: 进度', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10020, '研判意见', 'assessment_opinion', 1, '字典名称: 研判意见', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10021, '专家级别', 'expert_level', 1, '字典名称: 专家级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10022, '专家信息来源', 'expert_source', 1, '字典名称: 专家信息来源', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10023, '专家类型', 'expert_type', 1, '字典名称: 专家类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10024, '待办紧急程度', 'todo_urgency', 1, '字典名称: 待办紧急程度', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10025, '并购买方企业类型', 'acquisition_buyer_type', 1, '字典名称: 并购买方企业类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10026, '金融机构性质字典值', 'financial_nature', 1, '字典名称: 金融机构性质字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10027, '金融机构类型字典值', 'financial_type', 1, '字典名称: 金融机构类型字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10028, '基金类型字典值', 'fund_type', 1, '字典名称: 基金类型字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10029, '土地用途', 'land_usage', 1, '字典名称: 土地用途', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10030, '资源类型', 'resource_type', 1, '字典名称: 资源类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10031, '买方类型', 'buyer_type', 1, '字典名称: 买方类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10032, '上市板块', 'listing_board', 1, '字典名称: 上市板块', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10033, '问题类型', 'question_type', 1, '字典名称: 问题类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10034, '金融产品担保方式', 'guarantee_method', 1, '字典名称: 金融产品担保方式', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10035, '可用地情况', 'land_available', 1, '字典名称: 可用地情况', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10036, '融资需求/期限', 'financing_need_term', 1, '字典名称: 融资需求/期限', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10037, '合作伙伴级别', 'partner_level', 1, '字典名称: 合作伙伴级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10038, '园区类型', 'park_type', 1, '字典名称: 园区类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10039, '导入类型', 'import_type', 1, '字典名称: 导入类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10040, '行业领域', 'industry_sector', 1, '字典名称: 行业领域', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10041, '融资金额类型字典值', 'invest_amount_type', 1, '字典名称: 融资金额类型字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10042, '机构投资方式字典值', 'invest_method', 1, '字典名称: 机构投资方式字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10043, '投资区域', 'investment_area', 1, '字典名称: 投资区域', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10044, '投资类型', 'investment_type', 1, '字典名称: 投资类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10045, '需要投资人类型', 'investor_type', 1, '字典名称: 需要投资人类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10046, '项目阶段', 'project_stage', 1, '字典名称: 项目阶段', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10047, '活动相关方类型', 'activity_party_type', 1, '字典名称: 活动相关方类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10048, '结束提醒设置', 'reminder_end', 1, '字典名称: 结束提醒设置', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10049, '区县', 'district', 1, '字典名称: 区县', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10050, '线索阶段', 'lead_stage', 1, '字典名称: 线索阶段', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10051, '关联对象', 'related_object', 1, '字典名称: 关联对象', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10052, '所属产业', 'belong_industry', 1, '字典名称: 所属产业', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10053, '重要性', 'importance', 1, '字典名称: 重要性', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10054, '对接形式', 'contact_form', 1, '字典名称: 对接形式', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10055, '市局产业字典', 'city_industry', 1, '字典名称: 市局产业字典', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10056, '专家所属机构类型', '专家所属机构类型', 1, '字典名称: 专家所属机构类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10057, '运营状态字典值', 'operating_status', 1, '字典名称: 运营状态字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10058, '投资机构性质字典值', 'investor_nature', 1, '字典名称: 投资机构性质字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10059, '地块用途', 'plot_usage', 1, '字典名称: 地块用途', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10060, '金融产品类型字典值', 'financial_product_type', 1, '字典名称: 金融产品类型字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10061, '项目标签', 'project_label', 1, '字典名称: 项目标签', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10062, '并购买方需求公司类型', 'acquisition_buyer_need_company_type', 1, '字典名称: 并购买方需求公司类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10063, '可用地情况', 'land_available_1', 1, '字典名称: 可用地情况', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10064, '买方对赌要求', 'buyer_requirement', 1, '字典名称: 买方对赌要求', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10065, '平台公司', 'platform_company', 1, '字典名称: 平台公司', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10066, '并购买方需求类型', 'acquisition_buyer_need_type', 1, '字典名称: 并购买方需求类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10067, '币种字典表', 'currency', 1, '字典名称: 币种字典表', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10068, '企业注册类型字典值', 'enterprise_reg_type', 1, '字典名称: 企业注册类型字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10069, '轮次字典值', 'rounds', 1, '字典名称: 轮次字典值', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10070, '新研机构主责部门', 'research_department', 1, '字典名称: 新研机构主责部门', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10071, '优先级', 'priority', 1, '字典名称: 优先级', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10072, '日程活动级别', 'schedule_activity_level', 1, '字典名称: 日程活动级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10073, '日程活动类型', 'schedule_activity_type', 1, '字典名称: 日程活动类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10074, '日程参与状态', 'schedule_participation_status', 1, '字典名称: 日程参与状态', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10075, '日程类型分类', 'schedule_type', 1, '字典名称: 日程类型分类', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10076, '评分机构类别', 'score_org_category', 1, '字典名称: 评分机构类别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10077, '评分规则条件', 'score_rule_condition', 1, '字典名称: 评分规则条件', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10078, '待办重要性', 'todo_importance', 1, '字典名称: 待办重要性', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10079, '园区类型', 'park_type_1', 1, '字典名称: 园区类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10080, '融资需求/额度', 'financing_need_amount', 1, '字典名称: 融资需求/额度', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10081, '触发机制', 'trigger_mechanism', 1, '字典名称: 触发机制', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10082, '场景产业字典', 'scene_industry', 1, '字典名称: 场景产业字典', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10083, '金融机构级别', 'financial_level', 1, '字典名称: 金融机构级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10084, '开始提醒设置', 'reminder_start', 1, '字典名称: 开始提醒设置', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10085, '租金类型', 'rent_type', 1, '字典名称: 租金类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10086, '拜访对象', 'visit_object', 1, '字典名称: 拜访对象', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10087, '租金类型', 'rent_type_1', 1, '字典名称: 租金类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10088, '周几枚举', 'weekday', 1, '字典名称: 周几枚举', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10089, '完成状态', 'completion_status', 1, '字典名称: 完成状态', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10090, '产业支持类型', 'industry_support_type', 1, '字典名称: 产业支持类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10091, '项目来源', 'project_source', 1, '字典名称: 项目来源', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10092, '园区级别', 'park_level', 1, '字典名称: 园区级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10093, '项目类型', 'project_type', 1, '字典名称: 项目类型', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10094, '要素', '要素', 1, '字典名称: 要素', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10095, '逾期状态', '逾期状态', 1, '字典名称: 逾期状态', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10096, '园区级别', 'park_level_1', 1, '字典名称: 园区级别', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10097, 'bpm审批状态', 'bpm审批状态', 1, '字典名称: bpm审批状态', NOW(), NOW());
INSERT INTO `sys_dict` (`id`, `name`, `code`, `status`, `description`, `created_at`, `updated_at`) VALUES (10098, '在职状态', 'employee_status', 1, '字典名称: 在职状态', NOW(), NOW());

-- 字典项表数据
TRUNCATE TABLE `sys_dict_item`;

INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10001, '线索流转', '0', 1, 10001);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10002, '市局系统', '1', 1, 10001);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10003, '手动创建', '2', 1, 10001);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10004, '市领导交办', '0', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10005, '局领导交办', '1', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10006, '省里转办', '2', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10007, '省市重大活动对接', '3', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10008, '部门', '4', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10009, '区县', '5', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10010, '商协会', '6', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10011, '中介公司', '7', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10012, '大院大所', '8', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10013, '系统推送', '9', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10014, '平台公司', '10', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10015, '其他', '11', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10016, '合肥市投资促进有限公司', '12', 1, 10002);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10017, '已邀请', '0', 1, 10003);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10018, '已回复', '1', 1, 10003);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10019, '已报名', '2', 1, 10003);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10020, '已签到', '3', 1, 10003);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10021, '已留资', '4', 1, 10003);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10022, '世界500强', '0', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10023, '中国500强', '1', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10024, '央企', '2', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10025, '上市公司', '3', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10026, '国家专精特新小巨人', '4', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10027, '省级专精特新中小企业', '5', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10028, '高新技术企业', '6', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10029, '独角兽', '7', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10030, '瞪羚企业', '8', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10031, '中国零售50强', '9', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10032, '其他', '10', 1, 10004);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10033, '中国', '0', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10034, '江苏', '1', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10035, '英国', '2', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10036, '上海', '3', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10037, '欧洲', '4', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10038, '瑞士', '5', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10039, '北京', '6', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10040, '德国', '7', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10041, '广东', '8', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10042, '西班牙', '9', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10043, '深圳', '10', 1, 10005);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10044, '展会', '0', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10045, '培训', '1', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10046, '发布会', '2', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10047, '路演', '3', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10048, 'Open Day', '4', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10049, '广告投放', '5', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10050, 'KoL', '6', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10051, '媒体广告', '7', 1, 10006);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10052, '线下', '0', 1, 10007);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10053, '线上', '1', 1, 10007);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10054, '未生效', '0', 1, 10008);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10055, '已生效', '1', 1, 10008);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10056, '已作废', '2', 1, 10008);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10057, '10人以内', '0', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10058, '10-50', '1', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10059, '小于50人', '2', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10060, '50-100', '3', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10061, '100-500', '4', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10062, '500-1000', '5', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10063, '1000-5000', '6', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10064, '5000-10000', '7', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10065, '10000以上', '8', 1, 10009);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10066, '确认参加', '0', 1, 10010);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10067, '无法参加', '1', 1, 10010);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10068, '待定', '2', 1, 10010);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10069, '经研判不符合规划', '0', 1, 10011);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10070, '重复项目', '1', 1, 10011);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10071, '已有在谈或签约项目', '2', 1, 10011);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10072, '主办单位', '0', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10073, '协办单位', '1', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10074, '承办单位', '2', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10075, '支持单位', '3', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10076, '指导单位', '4', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10077, '赞助单位', '5', 1, 10012);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10078, '其他', '0', 1, 10013);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10079, '线索研判', '1', 1, 10013);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10080, '专项研判', '2', 1, 10013);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10081, '项目接待', '3', 1, 10013);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10082, 'A', '0', 1, 10014);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10083, 'A-', '1', 1, 10014);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10084, 'B', '2', 1, 10014);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10085, 'C', '3', 1, 10014);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10086, '市局线索', '0', 1, 10015);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10087, '投促公司线索', '1', 1, 10015);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10088, '外部机构线索', '2', 1, 10015);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10089, '并购线索', '3', 1, 10015);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10090, '动态（可重复获取，事件触发立即计算分值）', '0', 1, 10016);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10091, '静态（不可重复获取，基于最终结果计算分值）', '1', 1, 10016);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10092, '产业园区', '0', 1, 10017);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10093, '地块资源', '1', 1, 10017);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10094, '楼宇资源', '2', 1, 10017);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10095, '厂房资源', '3', 1, 10017);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10096, '企业', '0', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10097, '投资机构', '1', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10098, '金融机构', '2', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10099, '新研机构', '3', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10100, '专家库', '4', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10101, '场景', '5', 1, 10018);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10102, '对接', '0', 1, 10019);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10103, '立项', '1', 1, 10019);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10104, '尽调', '2', 1, 10019);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10105, '投决', '3', 1, 10019);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10106, '交割', '4', 1, 10019);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10107, '重点推进', '0', 1, 10020);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10108, '进一步推进', '1', 1, 10020);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10109, '保持推进', '2', 1, 10020);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10110, '不推进', '3', 1, 10020);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10111, '首席', '0', 1, 10021);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10112, '一般', '1', 1, 10021);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10113, '省发改委', '0', 1, 10022);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10114, '市科技局', '1', 1, 10022);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10115, '管理类', '0', 1, 10023);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10116, '财务金融类', '1', 1, 10023);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10117, '技术类', '2', 1, 10023);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10118, '紧急', '0', 1, 10024);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10119, '不紧急', '1', 1, 10024);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10120, '省属国企', '0', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10121, '市属国企', '1', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10122, '区属国企', '2', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10123, '市场化机构', '3', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10124, '民营企业', '4', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10125, '其他', '5', 1, 10025);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10126, '国有商业银行', '0', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10127, '央企', '1', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10128, '外资银行', '2', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10129, '省属国企', '3', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10130, '股份制商业银行', '4', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10131, '市属国企', '5', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10132, '城市商业银行', '6', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10133, '民企', '7', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10134, '农村商业银行', '8', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10135, '央企子公司', '9', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10136, '其他', '10', 1, 10026);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10137, '金融机构', '0', 1, 10027);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10138, '类金融机构', '1', 1, 10027);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10139, '券商机构', '2', 1, 10027);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10140, '保险机构', '3', 1, 10027);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10141, '与安徽省市区合作设立的母基金', '0', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10142, '与安徽省市区合作设立的直投基金', '1', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10143, '与其他省市区合作设立的母基金', '2', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10144, '与其他省市区合作设立的直投基金', '3', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10145, '其他市场化母基金', '4', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10146, '其他市场化直投基金', '5', 1, 10028);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10147, '工业用地', '0', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10148, '科研用地', '1', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10149, '商业用地', '2', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10150, '商办用地', '3', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10151, '仓储用地', '4', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10152, '文旅用地', '5', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10153, '商住用地', '6', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10154, '居住用地', '7', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10155, '文化设施', '8', 1, 10029);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10156, '投资机构', '0', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10157, '金融机构', '1', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10158, '新研机构', '2', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10159, '场景', '3', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10160, '区县', '4', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10161, '载体', '5', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10162, '金融产品', '6', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10163, '政策', '7', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10164, '并购买方', '8', 1, 10030);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10165, '企业', '0', 1, 10031);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10166, '投资机构', '1', 1, 10031);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10167, '上交所主板', '0', 1, 10032);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10168, '上交所科创板', '1', 1, 10032);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10169, '深交所主板', '2', 1, 10032);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10170, '深交所创业板', '3', 1, 10032);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10171, '北交所', '4', 1, 10032);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10172, '应用场景', '0', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10173, '环评指标', '1', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10174, '能评指标', '2', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10175, '政策支持', '3', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10176, '用地支持-用地指标', '4', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10177, '用地支持-规划调整', '5', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10178, '厂房支持', '6', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10179, '供应链对接', '7', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10180, '能源支持', '8', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10181, '股权', '9', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10182, '债权', '10', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10183, '资源对接需求', '11', 1, 10033);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10184, '抵押', '0', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10185, '抵押', '1', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10186, '质押', '2', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10187, '质押', '3', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10188, '信用', '4', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10189, '信用', '5', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10190, '保证', '6', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10191, '保证', '7', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10192, '担保', '8', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10193, '其他', '9', 1, 10034);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10194, '1	待征地', '0', 1, 10035);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10195, '2	熟地', '1', 1, 10035);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10196, '6个月以下', '0', 1, 10036);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10197, '6-12个月', '1', 1, 10036);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10198, '12-24个月', '2', 1, 10036);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10199, '24-36个月', '3', 1, 10036);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10200, '36个月以上', '4', 1, 10036);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10201, 'A级', '0', 1, 10037);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10202, 'B级', '1', 1, 10037);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10203, 'C级', '2', 1, 10037);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10204, '产业园区', '0', 1, 10038);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10205, '高新区', '1', 1, 10038);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10206, '开发区', '2', 1, 10038);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10207, '工业园', '3', 1, 10038);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10208, '小微园', '4', 1, 10038);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10209, '属性导入', '0', 1, 10039);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10210, '模板导入', '1', 1, 10039);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10211, '研发设计', '0', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10212, '工程服务', '1', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10213, '软件信息', '2', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10214, '现代物流', '3', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10215, '科创金融', '4', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10216, '检测认证', '5', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10217, '法律服务', '6', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10218, '会计审计', '7', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10219, '高端猎头', '8', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10220, '知识产权', '9', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10221, '贸易会展', '10', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10222, '创意文化（文旅）', '11', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10223, '商贸综合体', '12', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10224, '其他', '13', 1, 10040);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10225, '明确金额', '0', 1, 10041);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10226, '模糊金额', '1', 1, 10041);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10227, '未披露', '2', 1, 10041);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10228, '自有资金投资', '0', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10229, '母基金投资', '1', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10230, '子基金投资', '2', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10231, '领投', '3', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10232, '跟投', '4', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10233, '联合投资', '5', 1, 10042);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10234, '长三角地区', '0', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10235, '珠三角地区', '1', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10236, '环渤海地区', '2', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10237, '中部地区', '3', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10238, '西部地区', '4', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10239, '东北地区', '5', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10240, '京津冀地区', '6', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10241, '港澳台地区', '7', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10242, '国外', '8', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10243, '其他地区', '9', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10244, '其他地区', '10', 1, 10043);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10245, '新设', '0', 1, 10044);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10246, '增资', '1', 1, 10044);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10247, '并购', '2', 1, 10044);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10248, '产业投资人', '0', 1, 10045);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10249, '财务投资人', '1', 1, 10045);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10250, '产业及财务投资人', '2', 1, 10045);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10251, '接收项目', '0', 1, 10046);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10252, '项目研判', '1', 1, 10046);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10253, '项目在谈', '2', 1, 10046);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10254, '项目成功签约', '3', 1, 10046);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10255, '项目终止', '4', 1, 10046);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10256, '项目', '0', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10257, '线索', '1', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10258, '投资机构', '2', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10259, '新研机构', '3', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10260, '金融机构', '4', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10261, '场景', '5', 1, 10047);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10262, '不提醒', '0', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10263, '任务结束时', '1', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10264, '任务结束5分钟前', '2', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10265, '任务结束10分钟前', '3', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10266, '任务结束15分钟前', '4', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10267, '任务结束30分钟前', '5', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10268, '任务结束1小时前', '6', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10269, '任务结束2小时前', '7', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10270, '任务结束1天前', '8', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10271, '任务结束2天前', '9', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10272, '指定日期', '10', 1, 10048);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10273, '安巢经开区', '0', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10274, '巢湖市', '1', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10275, '庐江县', '2', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10276, '长丰县', '3', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10277, '肥西县', '4', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10278, '肥东县', '5', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10279, '蜀山区', '6', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10280, '瑶海区', '7', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10281, '包河区', '8', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10282, '庐阳区', '9', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10283, '新站高新区', '10', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10284, '经开区', '11', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10285, '高新区', '12', 1, 10049);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10286, '线索录入', '0', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10287, '线索研判', '1', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10288, '线索审核', '2', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10289, '审核完成', '3', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10290, '转化', '4', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10291, '终止', '5', 1, 10050);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10292, '项目', '0', 1, 10051);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10293, '线索', '1', 1, 10051);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10294, '新能源及智能网联汽车', '0', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10295, '新一代信息技术-集成电路', '1', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10296, '新一代信息技术-智能机器人', '2', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10297, '新一代信息技术-新型显示', '3', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10298, '新一代信息技术-智能城市', '4', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10299, '新一代信息技术-数字经济', '5', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10300, '新一代信息技术-人工智能', '6', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10301, '智能家电（居）', '7', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10302, '先进光伏及新型储能', '8', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10303, '生物医药', '9', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10304, '高端装备及新材料-新材料', '10', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10305, '高端装备及新材料-高端装备', '11', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10306, '节能环保与新能源（除光储）', '12', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10307, '量子信息与仪器', '13', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10308, '空天技术-空天信息与商业航天', '14', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10309, '空天技术-低空经济', '15', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10310, '聚变能源', '16', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10311, '生物制造', '17', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10312, '绿色食品及现代种业（现代农业和农产品加工）', '18', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10313, '文旅商贸和生活性服务业', '19', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10314, '生产性服务业', '20', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10315, '现代法务服务业', '21', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10316, '其他', '22', 1, 10052);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10317, 'A', '0', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10318, 'B', '1', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10319, 'B+', '2', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10320, 'C', '3', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10321, 'D', '4', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10322, '--', '5', 1, 10053);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10323, '外出赴企业考察', '0', 1, 10054);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10324, '来肥交流', '1', 1, 10054);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10325, '电话沟通', '2', 1, 10054);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10326, '线上会议', '3', 1, 10054);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10327, '智能网联新能源汽车', '0', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10328, '先进光伏及新型储能', '1', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10329, '数字经济', '2', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10330, '新材料', '3', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10331, '智能机器人', '4', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10332, '节能环保与新能源（除光储）', '5', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10333, '低空经济', '6', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10334, '生物医药', '7', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10335, '智能家电（居）', '8', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10336, '高端装备', '9', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10337, '量子信息与仪器', '10', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10338, '商业航天', '11', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10339, '聚变能源', '12', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10340, '生产性服务业', '13', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10341, '文旅商贸和生活性服务业', '14', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10342, '现代法务服务业', '15', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10343, '生物制造', '16', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10344, '现代农业与农产品加工业', '17', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10345, '新型显示', '18', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10346, '集成电路', '19', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10347, '人工智能', '20', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10348, '智能城市', '21', 1, 10055);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10349, '产业CVC', '0', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10350, '国家大基金管理人', '1', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10351, '国企国资', '2', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10352, '国资', '3', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10353, '省属国资', '4', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10354, '央企CVC', '5', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10355, '央企', '6', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10356, '高新区国资', '7', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10357, '市属国资', '8', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10358, '券商系', '9', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10359, '市场化', '10', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10360, 'FA', '11', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10361, '咨询机构', '12', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10362, '协会', '13', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10363, '家办', '14', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10364, '媒体', '15', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10365, '商会', '16', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10366, '资本金供应商', '17', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10367, '猎头公司', '18', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10368, '上市公司', '19', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10369, '省属国企', '20', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10370, '市属国企', '21', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10371, '民企', '22', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10372, '城商行', '23', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10373, '央企子公司', '24', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10374, '其他', '25', 1, 10056);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10375, '停止运营', '0', 1, 10057);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10376, '状态不明', '1', 1, 10057);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10377, '运营中', '2', 1, 10057);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10378, '市场化', '0', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10379, '产业CVC', '1', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10380, '央企CVC', '2', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10381, '省属国资', '3', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10382, '市属国资', '4', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10383, '区属国资', '5', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10384, '券商系', '6', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10385, '央企', '7', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10386, '国企', '8', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10387, 'FA', '9', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10388, '国资', '10', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10389, '高新区国资', '11', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10390, '国家大基金管理人', '12', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10391, '咨询机构', '13', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10392, '协会', '14', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10393, '家办', '15', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10394, '媒体', '16', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10395, '资本金供应商', '17', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10396, '猎头公司', '18', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10397, '上市公司', '19', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10398, '其他', '20', 1, 10058);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10399, '1	工业用地', '0', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10400, '2	科研用地', '1', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10401, '3	商业用地', '2', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10402, '4	商办用地', '3', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10403, '5	仓储用地', '4', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10404, '6	文旅用地', '5', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10405, '7	商住用地', '6', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10406, '8	居住用地', '7', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10407, '9	文化设施', '8', 1, 10059);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10408, '企业产品', '0', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10409, '疫情产品', '1', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10410, '政策产品', '2', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10411, '非银类产品', '3', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10412, '股权融资产品', '4', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10413, '秒批秒贷', '5', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10414, '热门产品', '6', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10415, '首贷中心', '7', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10416, '政信贷', '8', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10417, '区域政策产品', '9', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10418, '碳减排', '10', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10419, '支小再贷款', '11', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10420, '支农再贷款', '12', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10421, '科创金融', '13', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10422, '恵企产品', '14', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10423, '亩均英雄贷', '15', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10424, '债权融资', '16', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10425, '股权融资', '17', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10426, '投贷联动', '18', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10427, '股权融资（信易贷）', '19', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10428, '普惠金融', '20', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10429, '重点项目', '21', 1, 10060);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10430, '总部项目', '0', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10431, '制造基地', '1', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10432, '研发中心', '2', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10433, '销售中心', '3', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10434, '供应链中心', '4', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10435, '技改增资扩产', '5', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10436, '临规项目', '6', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10437, '腰部项目', '7', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10438, '元宇宙项目', '8', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10439, '光学项目', '9', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10440, '创业团队项目', '10', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10441, '其他', '11', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10442, '其他', '12', 1, 10061);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10443, '上市公司', '0', 1, 10062);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10444, '非上市公司', '1', 1, 10062);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10445, '待征地', '0', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10446, '熟地', '1', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10447, '计划未解决', '2', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10448, '已供地', '3', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10449, '已征收未供地', '4', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10450, '计划已解决', '5', 1, 10063);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10451, '有', '0', 1, 10064);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10452, '无', '1', 1, 10064);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10453, '产投', '0', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10454, '建投', '1', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10455, '兴泰', '2', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10456, '滨投', '3', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10457, '科大硅谷', '4', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10458, '文博集团', '5', 1, 10065);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10459, '控股', '0', 1, 10066);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10460, '参股', '1', 1, 10066);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10461, '控股和参股', '2', 1, 10066);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10462, '--', '0', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10463, '人民币', '1', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10464, '美元', '2', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10465, '港元', '3', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10466, '欧元', '4', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10467, '日元', '5', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10468, '英镑', '6', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10469, '新加坡元', '7', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10470, '加元', '8', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10471, '卢比', '9', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10472, '澳门元', '10', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10473, '澳大利亚元', '11', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10474, '瑞士法郎', '12', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10475, '新西兰元', '13', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10476, '韩元', '14', 1, 10067);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10477, '国有企业', '0', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10478, '集体企业', '1', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10479, '股份合作企业', '2', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10480, '联营企业', '3', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10481, '有限责任公司', '4', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10482, '股份有限公司', '5', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10483, '私营企业', '6', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10484, '其他内资企业', '7', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10485, '港、澳、台商投资企业', '8', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10486, '个人独资企业', '9', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10487, '有限合伙', '10', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10488, '普通合伙', '11', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10489, '外商投资企业', '12', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10490, '个体工商户', '13', 1, 10068);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10491, '种子轮', '0', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10492, '天使轮', '1', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10493, 'Pre-A轮', '2', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10494, 'A轮', '3', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10495, 'A+轮', '4', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10496, 'Pre-B轮', '5', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10497, 'B轮', '6', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10498, 'B+轮', '7', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10499, 'Pre-C轮', '8', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10500, 'C轮', '9', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10501, 'C+轮', '10', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10502, 'D轮', '11', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10503, 'E轮', '12', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10504, 'F轮', '13', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10505, 'G轮', '14', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10506, 'H轮', '15', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10507, 'I轮', '16', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10508, 'J轮', '17', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10509, 'K轮', '18', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10510, '战略投资', '19', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10511, 'Pre-IPO', '20', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10512, '已上市', '21', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10513, '并购', '22', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10514, '未融资', '23', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10515, '未知轮次', '24', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10516, '无需融资', '25', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10517, '已退市', '26', 1, 10069);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10518, '发改委', '0', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10519, '工信部', '1', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10520, '市科技局', '2', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10521, '市投资促进局', '3', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10522, '市委政法委', '4', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10523, '市农业农村局', '5', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10524, '市委金融办', '6', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10525, '市财政局', '7', 1, 10070);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10526, '高', '0', 1, 10071);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10527, '中', '1', 1, 10071);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10528, '低', '2', 1, 10071);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10529, 'A', '0', 1, 10072);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10530, 'B', '1', 1, 10072);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10531, 'C', '2', 1, 10072);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10532, 'D', '3', 1, 10072);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10533, '主题路演', '0', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10534, '线下资本对接', '1', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10535, '融资活动', '2', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10536, '项目线索研判', '3', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10537, '行业研讨会', '4', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10538, '生态活动', '5', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10539, '投融资研判', '6', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10540, '培训', '7', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10541, '其他', '8', 1, 10073);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10542, '待定', '0', 1, 10074);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10543, '参加', '1', 1, 10074);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10544, '拒绝', '2', 1, 10074);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10545, '日程', '0', 1, 10075);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10546, '活动', '1', 1, 10075);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10547, '金融机构奖惩规则', '0', 1, 10076);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10548, '投资机构奖惩规则', '1', 1, 10076);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10549, '包含任一', '0', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10550, '不包含', '1', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10551, '等于', '2', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10552, '不等于', '3', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10553, '大于', '4', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10554, '小于', '5', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10555, '大于等于', '6', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10556, '小于等于', '7', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10557, '介于（含边界）', '8', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10558, '介于（前闭后开）', '9', 1, 10077);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10559, '非常重要', '0', 1, 10078);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10560, '较为重要', '1', 1, 10078);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10561, '一般重要', '2', 1, 10078);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10562, '不重要', '3', 1, 10078);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10563, '1	产业园区', '0', 1, 10079);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10564, '2	高新区', '1', 1, 10079);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10565, '3	开发区', '2', 1, 10079);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10566, '4	工业园', '3', 1, 10079);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10567, '5	小微园', '4', 1, 10079);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10568, '100万以下', '0', 1, 10080);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10569, '100-200万', '1', 1, 10080);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10570, '200-500万', '2', 1, 10080);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10571, '500-1000万', '3', 1, 10080);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10572, '1000万以上', '4', 1, 10080);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10573, '系统自动触发', '0', 1, 10081);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10574, '手动触发', '1', 1, 10081);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10575, '集成电路', '0', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10576, '新型显示', '1', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10577, '量子产业', '2', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10578, '网络信息与安全', '3', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10579, '城市安全', '4', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10580, '空天信息', '5', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10581, '人工智能', '6', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10582, '新能源汽车和智能网联汽车', '7', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10583, '生物医药', '8', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10584, '新材料', '9', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10585, '高端装备', '10', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10586, '节能环保', '11', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10587, '光伏及新能源', '12', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10588, '绿色食品及现代种业', '13', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10589, '创意文化', '14', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10590, '智能家电', '15', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10591, '聚变能源', '16', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10592, '先进光伏及新型储能', '17', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10593, '合成生物', '18', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10594, '其他', '19', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10595, '低空经济', '20', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10596, '城市建管', '21', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10597, '民生服务', '22', 1, 10082);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10598, 'A', '0', 1, 10083);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10599, 'B', '1', 1, 10083);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10600, 'C', '2', 1, 10083);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10601, '不提醒', '0', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10602, '任务开始时', '1', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10603, '任务开始5分钟前', '2', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10604, '任务开始10分钟前', '3', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10605, '任务开始15分钟前', '4', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10606, '任务开始30分钟前', '5', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10607, '任务开始1小时前', '6', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10608, '任务开始2小时前', '7', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10609, '任务开始1天前', '8', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10610, '任务开始2天前', '9', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10611, '指定日期', '10', 1, 10084);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10612, '1	按面积算', '0', 1, 10085);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10613, '2	按单间算', '1', 1, 10085);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10614, '3	面议', '2', 1, 10085);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10615, '项目', '0', 1, 10086);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10616, '线索', '1', 1, 10086);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10617, '合作伙伴', '2', 1, 10086);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10618, '按面积算', '0', 1, 10087);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10619, '按单间算', '1', 1, 10087);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10620, '面议', '2', 1, 10087);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10621, '周一', '0', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10622, '周二', '1', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10623, '周三', '2', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10624, '周四', '3', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10625, '周五', '4', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10626, '周六', '5', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10627, '周日', '6', 1, 10088);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10628, '未完成', '0', 1, 10089);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10629, '已完成', '1', 1, 10089);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10630, '草稿', '2', 1, 10089);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10631, '1	研究院', '0', 1, 10090);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10632, '2	全国重点实验室', '1', 1, 10090);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10633, '3	新研机构', '2', 1, 10090);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10634, '4	其他', '3', 1, 10090);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10635, '市局项目', '0', 1, 10091);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10636, '投促公司项目', '1', 1, 10091);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10637, '外部机构项目', '2', 1, 10091);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10638, '国家级', '0', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10639, '省级', '1', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10640, '市级', '2', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10641, '区级', '3', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10642, '镇街级', '4', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10643, '其他', '5', 1, 10092);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10644, '项目', '0', 1, 10093);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10645, '在谈项目', '1', 1, 10093);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10646, '签约项目', '2', 1, 10093);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10647, '资本', '0', 1, 10094);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10648, '场景', '1', 1, 10094);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10649, '场地', '2', 1, 10094);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10650, '政策', '3', 1, 10094);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10651, '未逾期', '0', 1, 10095);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10652, '已逾期', '1', 1, 10095);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10653, '1	国家级', '0', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10654, '2	省级', '1', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10655, '3	市级', '2', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10656, '4	区级', '3', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10657, '5	镇街级', '4', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10658, '6	其他', '5', 1, 10096);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10659, '待提交', '0', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10660, '审批中', '1', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10661, '已完成', '2', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10662, '已驳回', '3', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10663, '已撤回', '4', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10664, '人工结束', '5', 1, 10097);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10665, '在职', '0', 1, 10098);
INSERT INTO `sys_dict_item` (`id`, `name`, `value`, `status`, `dict_id`) VALUES (10666, '离职', '1', 1, 10098);

SET FOREIGN_KEY_CHECKS = 1;